import type { Rikishi, RikishiStats } from "../types/rikishi";
import type { TacticalArchetype } from "../types/combat";

export function mockRikishi(id: string, overrides: Partial<Rikishi> = {}): Rikishi {
  return {
    id,
    shikona: `Wrestler-${id}`,
    heyaId: `heya-${id}`,
    nationality: "JP",
    rank: "maegashira",
    rankNumber: 5, division: "makuuchi",
    currentBashoWins: 3,
    currentBashoLosses: 1,
    side: "east",
    weight: 140,
    height: 180,
    style: "oshi",
    archetype: "all_rounder" as TacticalArchetype,
    power: 50,
    speed: 50,
    balance: 50,
    technique: 50,
    aggression: 50,
    experience: 50,
    momentum: 0,
    stamina: 100,
    fatigue: 0,
    injured: false,
    injuryWeeksRemaining: 0,
    birthYear: 1995,
    adaptability: 50,
    h2h: {},
    history: [],
    personalityTraits: [],
    condition: 90,
    motivation: 50,
    stats: { strength: 50, speed: 50, technique: 50, balance: 50, weight: 140, stamina: 100, mental: 50, adaptability: 50 } as RikishiStats,
    careerWins: 20,
    careerLosses: 10,
    favoredKimarite: [],
    weakAgainstStyles: [],
    ...overrides,
  } as unknown as Rikishi;
}