import type { PbpLibrary, Phrase, PhraseBucket } from "./pbp";

/** Expanded phrase library — high variety across all phases and buckets. */
export const DEFAULT_PBP_LIBRARY: PbpLibrary = {
  tachiai: {
    decisive: [
      { id: "t_dec_1",  text: "{winner} explodes off the shikirisen!", tags: ["crowd_roar"] },
      { id: "t_dec_2",  text: "A thunderous tachiai — {leader} wins the hit!" },
      { id: "t_dec_3",  text: "{leader} blasts forward and takes the initiative!" },
      { id: "t_dec_4",  text: "Devastating first contact! {leader} owns the opening moment.", tags: ["crowd_roar"] },
      { id: "t_dec_5",  text: "{leader} fires low and hard — {trailer} is immediately on the back foot!" },
      { id: "t_dec_6",  text: "Like a cannonball! {leader} detonates at the shikirisen!" },
      { id: "t_dec_7",  text: "The hit echoes through the hall. {leader} wins the tachiai decisively.", tags: ["crowd_roar"] },
      { id: "t_dec_8",  text: "{leader} gets the jump — and it's immediately, visibly, a problem for {trailer}." },
      { id: "t_dec_9",  text: "Perfect timing! {leader} is underneath and driving before {trailer} can react!" },
      { id: "t_dec_10", text: "A ferocious opening blow. {leader} establishes total control at the line." },
      { id: "t_dec_11", text: "{leader} drives the head into the chest — a brutally effective tachiai!" },
      { id: "t_dec_12", text: "No hesitation, no caution. {leader} commits everything and the result is immediate." },
      { id: "t_dec_13", text: "The collision is lopsided from the first millisecond. {leader} takes complete command.", tags: ["crowd_roar"] },
      { id: "t_dec_14", text: "{trailer} is rocked before the crowd even finishes exhaling." },
      { id: "t_dec_15", text: "A monstrous charge! {leader}'s tachiai tonight is something to behold." },
      { id: "t_dec_16", text: "{leader} bursts upward from the clay, catching {trailer} completely unprepared." },
      { id: "t_dec_17", text: "A breathtaking collision! {leader} claims the center immediately." },
      { id: "t_dec_18", text: "Pure velocity! {leader} converts momentum into absolute positional dominance." },
      { id: "t_dec_19", text: "The shikirisen might as well not exist. {leader} crosses it like a missile." },
      { id: "t_dec_20", text: "{leader} has been timing this for four minutes of shikiri. The execution is perfect." },
      { id: "t_dec_21", text: "A sledgehammer of a start! {leader} takes the inside track before {trailer} can blink." },
      { id: "t_dec_22", text: "Every ounce of body weight transferred on impact — {leader}'s tachiai was a weapon today." },
      { id: "t_dec_23", text: "The opening blast silences the arena for a split second. Then it erupts.", tags: ["crowd_roar"] },
      { id: "t_dec_24", text: "{trailer} had no counter for that. {leader} read the timing and fired first." },
      { id: "t_dec_25", text: "Head low, hips driving — {leader}'s tachiai form is impeccable under pressure." },
      { id: "t_dec_26", text: "The power differential is clear from the opening impact. {leader} took the day at that moment." },
    ],
    even: [
      { id: "t_even_1",  text: "They collide — neither gives an inch!" },
      { id: "t_even_2",  text: "Solid contact at the tachiai, straight into a battle!" },
      { id: "t_even_3",  text: "A hard charge from both men — dead even!" },
      { id: "t_even_4",  text: "Simultaneous impact! Both men absorb the blow without flinching." },
      { id: "t_even_5",  text: "They meet in the middle and the earth seems to hold still." },
      { id: "t_even_6",  text: "Equal force, equal will — the tachiai settles nothing." },
      { id: "t_even_7",  text: "A thunderclap of flesh on flesh. Neither man with any early advantage." },
      { id: "t_even_8",  text: "The charge is mutual and clean. Now the real work begins." },
      { id: "t_even_9",  text: "Both men hit their marks. No one flinches. The bout has truly begun." },
      { id: "t_even_10", text: "An even collision — the gyoji watches intently as they lock up." },
      { id: "t_even_11", text: "A mirror image at the tachiai! Neither can establish an early angle." },
      { id: "t_even_12", text: "Head to head, chest to chest! The impact is perfectly balanced." },
      { id: "t_even_13", text: "Both men hold their ground like ancient oaks. A true test of strength begins." },
      { id: "t_even_14", text: "The salt is still settling when the collision arrives. Dead even." },
      { id: "t_even_15", text: "Mutually destructive impact! Both men shudder, neither buckles." },
      { id: "t_even_16", text: "They meet in a wall of sound and fury — a perfect standoff." },
      { id: "t_even_17", text: "The gyoji does not move. There is no leader here. The bout begins afresh." },
      { id: "t_even_18", text: "The crowd had been holding its breath. Now it releases with a roar — no one dominated." },
      { id: "t_even_19", text: "Like two freight trains meeting head-on. Neither gives ground, neither gains it." },
      { id: "t_even_20", text: "It's as even as tachiai can be. The match will be decided elsewhere." },
    ],
    slow: [
      { id: "t_slow_1",  text: "A cautious tachiai… feeling for position." },
      { id: "t_slow_2",  text: "No wild rush — they meet and measure each other." },
      { id: "t_slow_3",  text: "Both men ease into contact. This will be a thinking man's bout." },
      { id: "t_slow_4",  text: "A deliberate, patient opening. Neither willing to overcommit early." },
      { id: "t_slow_5",  text: "Slow hands, slow feet. They are studying each other." },
      { id: "t_slow_6",  text: "The tachiai is careful — almost gentle. The danger will come later." },
      { id: "t_slow_7",  text: "A chess match begins. Neither man wants to be the first to blink." },
      { id: "t_slow_8",  text: "They meet softly and start to probe. The crowd senses a long one." },
      { id: "t_slow_9",  text: "A calculating start. {leader} refuses to rush the engagement." },
      { id: "t_slow_10", text: "They stand up slowly, eyes locked, daring the other to commit first." },
      { id: "t_slow_11", text: "The most careful tachiai in the arena today. Every centimeter of contact is deliberate." },
      { id: "t_slow_12", text: "Hands touch first. Then chests. Then the real conversation begins." },
      { id: "t_slow_13", text: "Neither man has committed. They are still in the negotiation phase." },
      { id: "t_slow_14", text: "A slow burn of an opening. The crowd shifts uneasily in their seats." },
      { id: "t_slow_15", text: "No fireworks at the tachiai. Just two careful men reading each other." },
      { id: "t_slow_16", text: "The veteran's tachiai — controlled, economical, giving nothing away." },
      { id: "t_slow_17", text: "They ease together like the tide coming in. Something is being calculated here." },
    ],
  },

  clinch: {
    grip_gain: [
      { id: "c_grip_1",  text: "{leader} gets a hand on the mawashi!", tags: ["crowd_roar"] },
      { id: "c_grip_2",  text: "Grip secured — {leader} wants yotsu!" },
      { id: "c_grip_3",  text: "{leader} finds the belt and settles in." },
      { id: "c_grip_4",  text: "There it is! {leader} snatches a grip on the canvas." },
      { id: "c_grip_5",  text: "{leader} digs a hand inside and the dynamic shifts immediately!" },
      { id: "c_grip_6",  text: "After a furious grip battle, {leader} finally secures the hold they wanted." },
      { id: "c_grip_7",  text: "{leader} threads the arm inside — a hard-fought grip is won." },
      { id: "c_grip_8",  text: "A clean grip! {leader} locks on and the pressure begins in earnest.", tags: ["crowd_roar"] },
      { id: "c_grip_9",  text: "{trailer} tried everything to deny it, but {leader} has the mawashi now." },
      { id: "c_grip_10", text: "{leader} earns a deep grip — patience rewarded." },
      { id: "c_grip_11", text: "{leader} snatches the thick fabric of the mawashi, anchoring their position." },
      { id: "c_grip_12", text: "A tactical masterstroke! {leader} finally secures the grip they've been hunting for." },
      { id: "c_grip_13", text: "The mawashi is won. The bout changes shape immediately." },
      { id: "c_grip_14", text: "{leader} snakes a hand to the back of the belt — a deep, dangerous grip." },
      { id: "c_grip_15", text: "The crowd murmurs as {leader} latches on. That grip position is lethal." },
      { id: "c_grip_16", text: "A hard-fought five seconds of grip battle, and {leader} emerges with the advantage." },
    ],
    grip_break: [
      { id: "c_break_1",  text: "{trailer} breaks the grip — back to the center!" },
      { id: "c_break_2",  text: "The hands come free — a reset in close quarters!" },
      { id: "c_break_3",  text: "A fierce wrenching motion and {trailer} strips the grip off the belt!" },
      { id: "c_break_4",  text: "{trailer} twists free — the hold is broken, the bout resets." },
      { id: "c_break_5",  text: "Hands come apart! {trailer} escapes the danger and creates distance." },
      { id: "c_break_6",  text: "{leader}'s grip is broken in a desperate, violent disengagement." },
      { id: "c_break_7",  text: "A savage grip break from {trailer} — back to neutral they go." },
      { id: "c_break_8",  text: "{trailer} pivots hard and sheds the hold. The bout starts over." },
      { id: "c_break_9",  text: "With a violent shudder, {trailer} snaps the grip away!" },
      { id: "c_break_10", text: "A desperate hip shift forces the hands apart. The danger is momentarily cleared." },
      { id: "c_break_11", text: "{trailer} uses the last of their energy to throw the grip off — bought time." },
      { id: "c_break_12", text: "The grip breaks with an audible slap of fabric. Both men breathe for a second." },
      { id: "c_break_13", text: "{trailer} yanks the arm out — not pretty, but effective. The grip is gone." },
      { id: "c_break_14", text: "A perfectly timed rotation and {leader}'s grip is gone before they realize it." },
    ],
    oshi_pressure: [
      { id: "c_oshi_1",  text: "{leader} pours on the tsuppari!", tags: ["crowd_roar"] },
      { id: "c_oshi_2",  text: "Heavy thrusts from {leader} — driving {trailer} back!" },
      { id: "c_oshi_3",  text: "{leader} keeps the chest up and shoves forward!" },
      { id: "c_oshi_4",  text: "No belt — just palms and momentum from {leader}!" },
      { id: "c_oshi_5",  text: "Pure oshi-zumo. {leader} wants nothing to do with the mawashi." },
      { id: "c_oshi_6",  text: "A wall of hands! {leader} drives forward, one thrust at a time." },
      { id: "c_oshi_7",  text: "{leader} builds a rhythm with the tsuppari — {trailer} can't get set." },
      { id: "c_oshi_8",  text: "The pressure is relentless. {leader} keeps {trailer} upright and moving backward." },
      { id: "c_oshi_9",  text: "No grip, no mercy — {leader} uses sheer forward pressure to dominate." },
      { id: "c_oshi_10", text: "{trailer}'s arms are scrambling to deflect the barrage from {leader}." },
      { id: "c_oshi_11", text: "{leader} stays tall and keeps the hands moving. Classic oshi pressure." },
      { id: "c_oshi_12", text: "The palms of {leader} land like pistons. {trailer} cannot plant their feet." },
      { id: "c_oshi_13", text: "Straight oshi — no deception, just force. {leader} is committed." },
      { id: "c_oshi_14", text: "The thrusts are not wild — they are aimed. {leader} targets the armpits deliberately." },
    ],
    scramble: [
      { id: "c_scr_1",  text: "No grip — just brute force and footwork!" },
      { id: "c_scr_2",  text: "A frantic scramble in the middle!" },
      { id: "c_scr_3",  text: "Hands fighting, hips turning — nothing settled yet!" },
      { id: "c_scr_4",  text: "Chaos at close quarters! Both men grappling for control." },
      { id: "c_scr_5",  text: "A wild, tangled exchange — the gyoji tracks every step." },
      { id: "c_scr_6",  text: "Neither man can establish anything clean. Pure wrestling instinct takes over." },
      { id: "c_scr_7",  text: "Limbs everywhere! This is sumo at its most primal." },
      { id: "c_scr_8",  text: "A messy battle for leverage — both men burning energy fast." },
      { id: "c_scr_9",  text: "No dominant position — just ferocity and noise." },
      { id: "c_scr_10", text: "The scramble is exhausting to watch. One of them must find an angle soon." },
      { id: "c_scr_11", text: "A flurry of desperate parries and feints! It's a chaotic wrestling match." },
      { id: "c_scr_12", text: "Neither gives an inch in this furious, untethered exchange of leverage." },
      { id: "c_scr_13", text: "Hands swatting, bodies colliding — the gyoji is barely keeping up." },
      { id: "c_scr_14", text: "Something has to give. This kind of scramble burns through a man's reserves." },
      { id: "c_scr_15", text: "It's ugly and it's beautiful. Pure improvised sumo in the center." },
    ],
    rear_attack: [
      { id: "c_rear_1", text: "{leader} slips to the side — danger from behind!", tags: ["gasps"] },
      { id: "c_rear_2", text: "Angle taken! {leader} has {trailer} twisted!" },
      { id: "c_rear_3", text: "{leader} circles behind — {trailer} is in serious trouble!", tags: ["gasps"] },
      { id: "c_rear_4", text: "A stunning positional shift! {leader} is at the back now." },
      { id: "c_rear_5", text: "{trailer} spins desperately, but {leader} has established the rear angle!" },
      { id: "c_rear_6", text: "{leader} works around the side and gets behind — almost impossible to recover from this." },
      { id: "c_rear_7", text: "Okuridashi territory! {leader} has slipped behind and the crowd knows it.", tags: ["crowd_roar"] },
      { id: "c_rear_8", text: "The side-step was fast enough that {trailer} has no idea where {leader} went." },
      { id: "c_rear_9", text: "From front to back in one fluid motion — {leader} is a different class." },
      { id: "c_rear_10", text: "{leader} has the body, has the angle — {trailer} can only spin and hope." },
    ],
    tsuppari_barrage: [
      { id: "str_tsup_1",  text: "A furious tsuppari barrage from {leader}!" },
      { id: "str_tsup_2",  text: "{leader} unleashes a relentless barrage of thrusts!" },
      { id: "str_tsup_3",  text: "Rapid-fire tsuppari! {leader} is overwhelming {trailer}!" },
      { id: "str_tsup_4",  text: "The thrusts come in a wave — {leader} dominates with tsuppari!" },
      { id: "str_tsup_5",  text: "{leader} rains down tsuppari on {trailer}'s defense!" },
      { id: "str_tsup_6",  text: "Machine-gun thrusts! {trailer} cannot find a counter." },
      { id: "str_tsup_7",  text: "The tempo is brutal. {leader}'s tsuppari rhythm is breaking {trailer} apart." },
      { id: "str_tsup_8",  text: "Thrust after thrust after thrust — {trailer}'s guard is crumbling." },
      { id: "str_tsup_9",  text: "{leader} switches angles mid-barrage to keep {trailer} guessing." },
      { id: "str_tsup_10", text: "A dazzling combination! The tsuppari from {leader} is pin-point tonight.", tags: ["crowd_roar"] },
      { id: "str_tsup_11", text: "{trailer} absorbs hit after hit. The question is how long they can hold." },
      { id: "str_tsup_12", text: "The tsuppari is so fast {trailer} can't even set their feet properly." },
      { id: "str_tsup_13", text: "One, two, three, four — the tsuppari from {leader} has no end." },
      { id: "str_tsup_14", text: "The crowd counts the hits under their breath. This barrage is relentless." },
      { id: "str_tsup_15", text: "{leader} targets the left shoulder, then the right — {trailer} is pinballing." },
      { id: "str_tsup_16", text: "Even {leader}'s misses are effective. The threat alone keeps {trailer} back." },
      { id: "str_tsup_17", text: "An upper tsuppari to the jaw forces {trailer}'s chin up and the hips to rise." },
    ],
    nodowa_pressure: [
      { id: "str_nod_1",  text: "A vicious nodowa! {leader} controls the throat!" },
      { id: "str_nod_2",  text: "{leader} applies suffocating nodowa pressure!" },
      { id: "str_nod_3",  text: "The hand goes to the throat — {leader} pushes back with nodowa!" },
      { id: "str_nod_4",  text: "{leader} drives {trailer} upward with a fierce nodowa!" },
      { id: "str_nod_5",  text: "Nodowa applied perfectly! {trailer} is gasping!" },
      { id: "str_nod_6",  text: "A crushing palm to the throat! {trailer}'s chin flies up." },
      { id: "str_nod_7",  text: "The nodowa is suffocating — {trailer} can barely keep their hips low." },
      { id: "str_nod_8",  text: "{leader} jabs the nodowa in deep. {trailer} stands straight and loses leverage instantly." },
      { id: "str_nod_9",  text: "Throat control established. {leader} uses it to dictate every movement." },
      { id: "str_nod_10", text: "{trailer} claws at the arm, but the nodowa grip is ironclad." },
      { id: "str_nod_11", text: "A sustained nodowa — {leader} is slowly strangling the fight out of {trailer}." },
      { id: "str_nod_12", text: "Every time {trailer} tries to lower the hips, {leader}'s palm drives the chin right back up." },
      { id: "str_nod_13", text: "The nodowa has {trailer} upright. That posture is a death sentence in sumo." },
      { id: "str_nod_14", text: "{leader} uses two arms — one nodowa, one pushing the armpit. Total control." },
      { id: "str_nod_15", text: "A sneering nodowa from {leader}. {trailer} has nowhere to put their weight." },
    ],
    harite_slap: [
      { id: "str_har_1",  text: "Crack! A sharp harite from {leader}!" },
      { id: "str_har_2",  text: "{leader} lands a ringing harite slap to the face!" },
      { id: "str_har_3",  text: "A stunning slap! {leader} uses harite effectively." },
      { id: "str_har_4",  text: "{trailer} stumbles after a powerful harite from {leader}!" },
      { id: "str_har_5",  text: "Harite! {leader} slaps the side of the face!" },
      { id: "str_har_6",  text: "The sound of the harite echoes across the arena.", tags: ["gasps"] },
      { id: "str_har_7",  text: "{leader} uses harite as a distraction and immediately follows with a push!" },
      { id: "str_har_8",  text: "An open hand stings {trailer}'s cheek! The crowd winces." },
      { id: "str_har_9",  text: "Two harite in quick succession from {leader}! {trailer}'s head is spinning." },
      { id: "str_har_10", text: "A vicious harite throws {trailer}'s balance for a critical second — and {leader} exploits it." },
      { id: "str_har_11", text: "The harite lands flush. For a moment, {trailer} looks lost." },
      { id: "str_har_12", text: "{leader} opens with a harite and immediately goes for the inside. Classic combination." },
      { id: "str_har_13", text: "A backhand harite — unusual but completely effective. {trailer}'s neck snaps sideways." },
      { id: "str_har_14", text: "The crowd reacts before {trailer} does. That harite was perfectly timed." },
    ],
    throat_attack: [
      { id: "str_thr_1",  text: "{leader} attacks the throat directly!" },
      { id: "str_thr_2",  text: "A dangerous thrust to the throat from {leader}!" },
      { id: "str_thr_3",  text: "{leader} aims high and catches the throat!" },
      { id: "str_thr_4",  text: "{trailer}'s chin is forced up by {leader}'s throat attack!" },
      { id: "str_thr_5",  text: "Direct throat pressure! {leader} takes command!" },
      { id: "str_thr_6",  text: "The throat thrust snaps {trailer}'s posture upright — a nightmare position." },
      { id: "str_thr_7",  text: "{leader} goes high and straight — palm driving into the throat." },
      { id: "str_thr_8",  text: "A targeted attack! {leader} goes for the throat and finds it cleanly." },
      { id: "str_thr_9",  text: "{trailer} struggles to lower their hips with a hand at their throat." },
      { id: "str_thr_10", text: "Both hands on the throat — {leader} controls {trailer}'s entire posture." },
      { id: "str_thr_11", text: "A stiff-arm into the throat. {trailer} is forced back and upright in the same motion." },
      { id: "str_thr_12", text: "The throat attack is {leader}'s calling card, and they've just signed their name." },
    ],
    shoulder_blast: [
      { id: "str_shl_1",  text: "{leader} leads with a devastating shoulder blast!" },
      { id: "str_shl_2",  text: "A heavy shoulder hit! {leader} crashes into {trailer}!" },
      { id: "str_shl_3",  text: "{leader} uses the shoulder to blast {trailer} backward!" },
      { id: "str_shl_4",  text: "Shoulder first, {leader} clears space forcefully." },
      { id: "str_shl_5",  text: "A solid shoulder blast disrupts {trailer}'s balance!" },
      { id: "str_shl_6",  text: "{leader} drops the shoulder and drives through like a freight train." },
      { id: "str_shl_7",  text: "A bull rush! {leader} leads with the shoulder and leaves {trailer} reeling.", tags: ["crowd_roar"] },
      { id: "str_shl_8",  text: "The shoulder connects with a sickening thud. {trailer} is shifted." },
      { id: "str_shl_9",  text: "{leader} times the shoulder blast perfectly — {trailer} was just leaning in." },
      { id: "str_shl_10", text: "A rolling shoulder hit. The mass behind it is enormous and {trailer} feels every kilogram." },
      { id: "str_shl_11", text: "{leader} ducks low and comes up with the shoulder right under {trailer}'s armpit." },
      { id: "str_shl_12", text: "Shoulder, then body — {leader} turns the blast into a full drive." },
    ],
    migi_yotsu_established: [
      { id: "grp_mig_1",  text: "{leader} locks in a deep migi-yotsu grip!" },
      { id: "grp_mig_2",  text: "Right hand inside — migi-yotsu is established for {leader}!" },
      { id: "grp_mig_3",  text: "The grip battle ends with {leader} securing migi-yotsu." },
      { id: "grp_mig_4",  text: "{leader} finds the right-inside position. Perfect migi-yotsu!" },
      { id: "grp_mig_5",  text: "Migi-yotsu! {leader} has the exact grip they wanted." },
      { id: "grp_mig_6",  text: "{leader} confidently slides the right hand inside for migi-yotsu." },
      { id: "grp_mig_7",  text: "The right hand is firmly inside! {leader} establishes migi-yotsu." },
      { id: "grp_mig_8",  text: "A textbook migi-yotsu grip from {leader}! The advantage is clear." },
      { id: "grp_mig_9",  text: "{leader} wins the grip fight, securing a beautiful migi-yotsu." },
      { id: "grp_mig_10", text: "Migi-yotsu locked in! {leader} controls the grappling exchange." },
      { id: "grp_mig_11", text: "The right hand snakes inside and finds the canvas. Migi-yotsu!" },
      { id: "grp_mig_12", text: "{leader} has waited for this position all bout — the migi-yotsu is finally his." },
      { id: "grp_mig_13", text: "Deep right-hand inside. {leader} settles into a commanding migi-yotsu." },
      { id: "grp_mig_14", text: "The right arm pries its way inside. Migi-yotsu and the crowd stirs." },
      { id: "grp_mig_15", text: "{leader} uses the tachiai momentum to thread the right arm. A seamless entry." },
      { id: "grp_mig_16", text: "Migi-yotsu — {leader}'s strongest grip, and they've got it deep and tight." },
    ],
    hidari_yotsu_established: [
      { id: "grp_hid_1",  text: "{leader} secures a strong hidari-yotsu position!" },
      { id: "grp_hid_2",  text: "Left hand inside! {leader} gets hidari-yotsu." },
      { id: "grp_hid_3",  text: "A masterful transition into hidari-yotsu by {leader}." },
      { id: "grp_hid_4",  text: "{leader} forces the hidari-yotsu grip — a dangerous setup!" },
      { id: "grp_hid_5",  text: "Hidari-yotsu established! {leader} controls the inside left." },
      { id: "grp_hid_6",  text: "A swift left hand inside — {leader} secures hidari-yotsu." },
      { id: "grp_hid_7",  text: "{leader} dominates the inside track with a hidari-yotsu grip." },
      { id: "grp_hid_8",  text: "Hidari-yotsu! {leader} has the left-inside advantage." },
      { id: "grp_hid_9",  text: "The left hand finds its mark. {leader} locks in hidari-yotsu!" },
      { id: "grp_hid_10", text: "{leader} expertly maneuvers into a commanding hidari-yotsu hold." },
      { id: "grp_hid_11", text: "Left arm in deep — hidari-yotsu, and {leader} looks very dangerous." },
      { id: "grp_hid_12", text: "{leader} hunts the left-inside and claims it. Hidari-yotsu established." },
      { id: "grp_hid_13", text: "The inside left is won. {leader} adjusts the hips and begins to work." },
      { id: "grp_hid_14", text: "A disguised entry from {leader}. The left arm was inside before {trailer} registered." },
      { id: "grp_hid_15", text: "Hidari-yotsu and {leader} is already thinking about the uwatenage." },
      { id: "grp_hid_16", text: "The left hand on the rear of the mawashi — {leader} has a deep and dangerous grip." },
    ],
    double_inside: [
      { id: "grp_dbl_1",  text: "Double inside! {leader} dominates the grip completely!" },
      { id: "grp_dbl_2",  text: "{leader} gets both hands inside — a huge advantage!", tags: ["crowd_roar"] },
      { id: "grp_dbl_3",  text: "An ironclad double-inside grip from {leader}." },
      { id: "grp_dbl_4",  text: "{leader} controls the center with a double-inside hold." },
      { id: "grp_dbl_5",  text: "Moro-zashi! {leader} has double inside control!", tags: ["crowd_roar"] },
      { id: "grp_dbl_6",  text: "Both arms inside! The advantage is total. {trailer} is in desperate trouble." },
      { id: "grp_dbl_7",  text: "Moro-zashi secured! This bout could be over very quickly." },
      { id: "grp_dbl_8",  text: "{leader} claims both inside positions. The leverage is overwhelming." },
      { id: "grp_dbl_9",  text: "A rare double-inside grip — and {leader} has it locked." },
      { id: "grp_dbl_10", text: "{trailer} has no answer for the moro-zashi. Both arms are compromised." },
      { id: "grp_dbl_11", text: "The moro-zashi is considered unbeatable. {trailer} must escape or this ends badly.", tags: ["crowd_roar"] },
      { id: "grp_dbl_12", text: "Both hands are deep inside the belt. {leader} stands tall and begins the drive." },
      { id: "grp_dbl_13", text: "{trailer} desperately flails at the outside, but {leader}'s moro-zashi is unshakeable." },
      { id: "grp_dbl_14", text: "There is no more dangerous grip in sumo. {leader} has it. The crowd understands." },
    ],
    over_under: [
      { id: "grp_ovu_1", text: "{leader} secures an over-under grip on the belt." },
      { id: "grp_ovu_2", text: "An even over-under position, but {leader} drives the action." },
      { id: "grp_ovu_3", text: "Over-under established! A classic grappling stance." },
      { id: "grp_ovu_4", text: "{leader} settles into an over-under clinch." },
      { id: "grp_ovu_5", text: "The hands lock in an over-under battle!" },
      { id: "grp_ovu_6", text: "A mutual over-under — the bout enters its grinding, tactical phase." },
      { id: "grp_ovu_7", text: "Over-under. Neither man is comfortable, but {leader} looks to impose." },
      { id: "grp_ovu_8", text: "{leader} accepts the over-under and immediately looks for a step." },
      { id: "grp_ovu_9", text: "One hand over, one under — a balanced position that hides its own tensions." },
      { id: "grp_ovu_10", text: "The over-under locks them together. Now it's about hips and timing." },
      { id: "grp_ovu_11", text: "Classic yotsu-zumo. One over, one under. The match becomes a battle of leverage." },
      { id: "grp_ovu_12", text: "{leader} works the over-under with deliberate patience. Waiting for the right angle." },
    ],
    no_grip_scramble: [
      { id: "grp_nog_1",  text: "A chaotic no-grip scramble ensues!" },
      { id: "grp_nog_2",  text: "Hands are flying — no one can find the mawashi!" },
      { id: "grp_nog_3",  text: "Both men fighting for a hold in a wild scramble." },
      { id: "grp_nog_4",  text: "A messy, no-grip exchange in the center." },
      { id: "grp_nog_5",  text: "No grip yet! Just pure scramble and hustle." },
      { id: "grp_nog_6",  text: "Frantic hands, shifting hips — nobody has established anything clean." },
      { id: "grp_nog_7",  text: "Neither man can get on the mawashi. The bout is all footwork right now." },
      { id: "grp_nog_8",  text: "A wrestling scramble with no resolution — the crowd is tense." },
      { id: "grp_nog_9",  text: "The mawashi is being denied by both men. Something will have to break." },
      { id: "grp_nog_10", text: "Pure no-belt warfare. Hands batting away hands. The gyoji watches the feet." },
      { id: "grp_nog_11", text: "No one has the belt, but no one needs it right now. Footwork is everything." },
      { id: "grp_nog_12", text: "The grip battle is a war of its own. This is sumo before the sumo." },
    ],
  },

  momentum: {
    edge_dance: [
      { id: "m_edge_1", text: "{trailer} teeters at the tawara!", tags: ["gasps", "close_call"] },
      { id: "m_edge_2", text: "Heels on the straw — {trailer} somehow stays in!", tags: ["gasps", "close_call"] },
      { id: "m_edge_3", text: "A tight rope act at the edge!" },
      { id: "m_edge_4", text: "The gyoji leans in — {trailer} is right at the boundary!", tags: ["gasps"] },
      { id: "m_edge_5", text: "{trailer} is balanced on nothing. The dohyo is about to claim a victim.", tags: ["gasps"] },
      { id: "m_edge_6", text: "Right at the bales! {trailer} needs a miracle here." },
      { id: "m_edge_7", text: "{trailer} is half out! The crowd holds its collective breath." },
      { id: "m_edge_8", text: "Out of room! {trailer} is pressed against the tawara with nowhere to go." },
      { id: "m_edge_9", text: "The bales are brushing {trailer}'s heel. The end is very near." },
      { id: "m_edge_10", text: "A tightrope walk at the boundary. {trailer} defies gravity for one more second." },
      { id: "m_edge_11", text: "{trailer} rocks back and somehow forwards. The dohyo will not release them yet." },
    ],
    counter_turn: [
      { id: "m_ctr_1",  text: "A sudden counter — {leader} turns the tables!", tags: ["crowd_roar"] },
      { id: "m_ctr_2",  text: "{leader} absorbs it and redirects the force!" },
      { id: "m_ctr_3",  text: "That timing! {leader} steals the advantage!" },
      { id: "m_ctr_4",  text: "A clinical reversal! {leader} uses {trailer}'s own momentum against them." },
      { id: "m_ctr_5",  text: "The counter arrives like a thunderbolt! {leader} is back in this!", tags: ["crowd_roar"] },
      { id: "m_ctr_6",  text: "{leader} waits, waits, and then — the counter! Perfect timing." },
      { id: "m_ctr_7",  text: "A sudden pivot! {leader} has turned the entire bout around." },
      { id: "m_ctr_8",  text: "{trailer} overextends, and {leader} capitalizes with a swift counter." },
      { id: "m_ctr_9",  text: "The momentum swings like a pendulum! {leader} is suddenly in control." },
      { id: "m_ctr_10", text: "{leader} shifts the center of gravity, utterly neutralizing {trailer}'s drive." },
      { id: "m_ctr_11", text: "A brilliant tactical retreat from {leader} opens the door for a fierce counter-attack!" },
      { id: "m_ctr_12", text: "The trap snaps shut. {leader} was giving ground on purpose." },
      { id: "m_ctr_13", text: "A veteran move — {leader} lets {trailer} over-commit and then answers." },
      { id: "m_ctr_14", text: "{trailer} pushed too hard and {leader} found the leverage. The tables have turned." },
      { id: "m_ctr_15", text: "Brilliant ring craft. {leader} manufactured that opening out of nothing." },
    ],
    fatigue_swing: [
      { id: "m_fat_1",  text: "You can see the strain — momentum swings!", tags: ["gasps"] },
      { id: "m_fat_2",  text: "{trailer} slows… and {leader} surges!" },
      { id: "m_fat_3",  text: "The pace is taking its toll. {trailer} is visibly fading." },
      { id: "m_fat_4",  text: "{trailer}'s legs are heavy now. {leader} smells blood." },
      { id: "m_fat_5",  text: "The longer this goes, the better it looks for {leader}." },
      { id: "m_fat_6",  text: "{trailer} gasps between exchanges. The tank is nearly empty." },
      { id: "m_fat_7",  text: "Fatigue is the great equalizer. {trailer} can feel it in every step." },
      { id: "m_fat_8",  text: "The thighs are burning. {trailer} cannot find the burst they need." },
      { id: "m_fat_9",  text: "{leader} is still strong. That disparity is now the entire story." },
      { id: "m_fat_10", text: "{trailer}'s arms drop a fraction. {leader} notices immediately." },
      { id: "m_fat_11", text: "The body language says everything. {trailer} has nothing left to give." },
      { id: "m_fat_12", text: "A long, grinding bout and the heavier man's fitness is showing its limits." },
    ],
    steady_drive: [
      { id: "m_drv_1",  text: "{leader} keeps walking forward — relentless pressure." },
      { id: "m_drv_2",  text: "A steady march from {leader} — no room to breathe." },
      { id: "m_drv_3",  text: "{leader} advances methodically. There is no panic here — just pressure." },
      { id: "m_drv_4",  text: "Inexorable forward movement from {leader}. {trailer} can only retreat." },
      { id: "m_drv_5",  text: "A slow, grinding drive! {leader} earns every centimeter." },
      { id: "m_drv_6",  text: "{leader} is a machine. The drive continues without pause." },
      { id: "m_drv_7",  text: "Steady, heavy, inevitable. {trailer} is being walked to the edge." },
      { id: "m_drv_8",  text: "The pressure is constant and suffocating. {trailer} cannot find a foothold." },
      { id: "m_drv_9",  text: "One step. Two steps. Three steps. The drive from {leader} does not stop." },
      { id: "m_drv_10", text: "{trailer} plants, absorbs, and still moves backward. {leader} wills them toward the straw." },
      { id: "m_drv_11", text: "The legs of {leader} churn like pistons. The direction is always forward." },
      { id: "m_drv_12", text: "{trailer} tries to angle away but {leader} adjusts and drives on." },
    ],
    bales_at_tawara: [
      { id: "edg_bal_1",  text: "{trailer} is backed right against the tawara bales!" },
      { id: "edg_bal_2",  text: "The bales are the only thing keeping {trailer} in!" },
      { id: "edg_bal_3",  text: "{trailer} feels the straw — right at the edge!" },
      { id: "edg_bal_4",  text: "Danger! {trailer} is pushed onto the bales!" },
      { id: "edg_bal_5",  text: "{trailer}'s heels hit the tawara!" },
      { id: "edg_bal_6",  text: "The tawara presses into {trailer}'s heels. One more step ends this." },
      { id: "edg_bal_7",  text: "Backed up! {trailer} has no real estate left." },
      { id: "edg_bal_8",  text: "{trailer} is against the straw boundary. The crowd leans forward." },
      { id: "edg_bal_9",  text: "The bales are there. {leader} knows it. {trailer} can feel it." },
      { id: "edg_bal_10", text: "The straw meets the heel. The gyoji shifts their grip on the gunbai." },
      { id: "edg_bal_11", text: "Against the tawara — {trailer}'s options have narrowed to almost nothing." },
    ],
    steps_out_then_recovers: [
      { id: "edg_rec_1", text: "{trailer} nearly steps out but somehow recovers!" },
      { id: "edg_rec_2", text: "A miraculous recovery from {trailer} at the very edge!" },
      { id: "edg_rec_3", text: "{trailer} dances on the line and pushes back inside!" },
      { id: "edg_rec_4", text: "Looked like a step out, but {trailer} survives and recovers!" },
      { id: "edg_rec_5", text: "An impossible save! {trailer} pulls back from the brink." },
      { id: "edg_rec_6", text: "The foot touches down, then lifts — {trailer} refuses to go!" },
      { id: "edg_rec_7", text: "The crowd gasps, then roars! {trailer} has survived the impossible.", tags: ["crowd_roar", "gasps"] },
      { id: "edg_rec_8", text: "{trailer} is back in bounds! Sheer survival instinct at work." },
      { id: "edg_rec_9", text: "A foot outside, then pulled back before the gyoji could see — or could they?" },
      { id: "edg_rec_10", text: "Defying the laws of balance, {trailer} finds the inside of the ring again." },
    ],
    heel_on_straw: [
      { id: "edg_hel_1", text: "{trailer}'s heel is squarely on the straw!" },
      { id: "edg_hel_2", text: "One heel rests dangerously on the boundary line." },
      { id: "edg_hel_3", text: "The gyoji watches closely — {trailer}'s heel is on the straw!" },
      { id: "edg_hel_4", text: "{trailer} balances precariously with a heel on the tawara." },
      { id: "edg_hel_5", text: "A heel touches the straw — {trailer} has no room left!" },
      { id: "edg_hel_6", text: "One more push and that heel becomes a loss." },
      { id: "edg_hel_7", text: "The heel is down on the straw bales. The gyoji has seen it." },
      { id: "edg_hel_8", text: "{trailer} walks a razor's edge — literally. That heel is all the way back." },
      { id: "edg_hel_9", text: "The straw is touching the heel. The crowd has gone perfectly quiet." },
      { id: "edg_hel_10", text: "Not out yet, but a millimeter away from it. The gyoji's fan trembles." },
    ],
    dancing_escape: [
      { id: "edg_dan_1", text: "A beautiful dancing escape along the edge by {trailer}!" },
      { id: "edg_dan_2", text: "{trailer} pirouettes along the bales to stay alive!" },
      { id: "edg_dan_3", text: "Nimble footwork! {trailer} dances out of danger." },
      { id: "edg_dan_4", text: "{trailer} skirts the edge with a dancer's grace." },
      { id: "edg_dan_5", text: "A spinning, dancing escape saves {trailer}!" },
      { id: "edg_dan_6", text: "{trailer} glides along the tawara, somehow keeping two feet in bounds." },
      { id: "edg_dan_7", text: "An athletic escape! {trailer} uses footwork that belongs in a different sport." },
      { id: "edg_dan_8", text: "{trailer} traces the boundary line like a tightrope walker. The crowd is stunned." },
      { id: "edg_dan_9", text: "A balletic escape from {trailer}! The heya will be watching this clip for years." },
      { id: "edg_dan_10", text: "{trailer} skips along the tawara at full speed — still in bounds, still alive." },
    ],
    turns_the_tables: [
      { id: "edg_tur_1", text: "At the very edge, {trailer} turns the tables!", tags: ["crowd_roar"] },
      { id: "edg_tur_2", text: "A stunning reversal at the tawara! {trailer} strikes back!", tags: ["crowd_roar"] },
      { id: "edg_tur_3", text: "{trailer} uses the boundary to pivot and turn the tables!" },
      { id: "edg_tur_4", text: "From the brink of defeat, {trailer} flips the momentum!" },
      { id: "edg_tur_5", text: "An edge counter! The tables are completely turned!" },
      { id: "edg_tur_6", text: "Utchari! {trailer} plants and twists at the very last moment!", tags: ["crowd_roar"] },
      { id: "edg_tur_7", text: "With back to the crowd, {trailer} somehow reverses the whole situation." },
      { id: "edg_tur_8", text: "{leader} had it won. Then {trailer} found one last desperate burst." },
      { id: "edg_tur_9", text: "The tawara became {trailer}'s ally. The reversal is complete and the crowd cannot believe it." },
      { id: "edg_tur_10", text: "A sudden twist with the back against the straw — and {leader} is the one stumbling now." },
    ],
    slips_but_survives: [
      { id: "edg_slp_1", text: "{trailer} slips on the clay but survives the push!" },
      { id: "edg_slp_2", text: "A loss of footing! But {trailer} somehow stays in!" },
      { id: "edg_slp_3", text: "{trailer} stumbles and slips, yet refuses to go down!" },
      { id: "edg_slp_4", text: "A dangerous slip is met with an incredible survival instinct." },
      { id: "edg_slp_5", text: "Despite a clear slip, {trailer} holds on and survives!" },
      { id: "edg_slp_6", text: "A foot gives way — but {trailer} finds the ground before going over!" },
      { id: "edg_slp_7", text: "Slipping, stumbling, but still upright! {trailer} has escaped somehow." },
      { id: "edg_slp_8", text: "The clay betrays {trailer}'s foot — but willpower keeps them in the bout." },
      { id: "edg_slp_9", text: "The foot slides out and the body leans — then, impossibly, {trailer} recovers." },
      { id: "edg_slp_10", text: "A stumble that should have ended it. That {trailer} is still standing is a small miracle." },
    ],
    grip_change: [
      { id: "m_gc_1",  text: "{leader} shifts the grip — hunting for a better angle!", tags: ["crowd_roar"] },
      { id: "m_gc_2",  text: "A sudden grip adjustment from {leader} catches {trailer} off guard!" },
      { id: "m_gc_3",  text: "{leader} releases and re-grabs — the mawashi changes hands!" },
      { id: "m_gc_4",  text: "Smart wrestling from {leader}, swapping to a stronger inside grip." },
      { id: "m_gc_5",  text: "{leader} reads the position and transitions to a fresh hold on the belt." },
      { id: "m_gc_6",  text: "The grip switch is fast and deliberate. {trailer} had no time to react." },
      { id: "m_gc_7",  text: "{leader} abandons the outside grip and goes hunting for the inside. Patient." },
      { id: "m_gc_8",  text: "A seamless grip change! {leader} upgrades their hold mid-battle." },
      { id: "m_gc_9",  text: "{leader} lets go with one hand, pivots, and regrabs in a single flowing motion." },
      { id: "m_gc_10", text: "A calculated risk — {leader} releases a solid hold to find a better one." },
      { id: "m_gc_11", text: "The old grip is abandoned. {leader} hunts the new position with total confidence." },
    ],
    footwork_angle: [
      { id: "m_fa_1",  text: "{leader} shuffles the feet and cuts a brutal new angle!" },
      { id: "m_fa_2",  text: "A sharp lateral step from {leader} — geometry shifts in their favor." },
      { id: "m_fa_3",  text: "{leader} pivots, redirecting the whole fight with a single footwork adjustment." },
      { id: "m_fa_4",  text: "The footwork from {leader} is exceptional — {trailer} is suddenly exposed." },
      { id: "m_fa_5",  text: "{leader} finds the angle that {trailer} cannot cover. Masterful positioning." },
      { id: "m_fa_6",  text: "A half-step to the side opens the whole dohyo for {leader}." },
      { id: "m_fa_7",  text: "{leader} shuffles laterally and the fight changes shape entirely." },
      { id: "m_fa_8",  text: "Brilliant ring IQ! {leader} finds the crease with precise footwork." },
      { id: "m_fa_9",  text: "A quick sidestep and {trailer}'s momentum carries them into empty air." },
      { id: "m_fa_10", text: "{leader} creates the angle with their feet, not their arms. Economy of movement." },
      { id: "m_fa_11", text: "The footwork is almost invisible. The result is enormous." },
      { id: "m_fa_12", text: "{leader} opens the gap with a single, perfectly-timed step to the side." },
    ],
    mistake: [
      { id: "m_mis_1",  text: "{trailer} overcommits — and {leader} makes them pay!", tags: ["crowd_roar"] },
      { id: "m_mis_2",  text: "A fatal lunge from {trailer}! {leader} seizes the opening instantly." },
      { id: "m_mis_3",  text: "{trailer} reaches too far — the balance is gone!" },
      { id: "m_mis_4",  text: "A momentary lapse from {trailer}, and {leader} is already capitalizing." },
      { id: "m_mis_5",  text: "Costly mistake! {trailer} loses their center and the momentum swings." },
      { id: "m_mis_6",  text: "{trailer} lunges forward and finds nothing — {leader} sidestepped!" },
      { id: "m_mis_7",  text: "The error is small. The consequence is enormous. {leader} pounces." },
      { id: "m_mis_8",  text: "{trailer} telegraphs the move and {leader} has read it perfectly." },
      { id: "m_mis_9",  text: "A split-second of lost concentration from {trailer} and {leader} is already through." },
      { id: "m_mis_10", text: "The over-extension is punished immediately. {leader} shows no mercy." },
      { id: "m_mis_11", text: "{trailer} gambled on an attack that didn't connect — and now {leader} holds the advantage." },
      { id: "m_mis_12", text: "One foot too far forward and {trailer}'s center disappears entirely." },
    ],
    tachiai_win: [
      { id: "m_tw_1", text: "The tachiai advantage is telling — {leader} has dictated the whole bout!" },
      { id: "m_tw_2", text: "{leader}'s first-step dominance is bearing fruit deep into the bout." },
      { id: "m_tw_3", text: "From that opening collision, {leader} has never let {trailer} get comfortable." },
      { id: "m_tw_4", text: "The momentum from the tachi-ai keeps paying dividends for {leader}." },
      { id: "m_tw_5", text: "That first-step win is still reverberating. {trailer} has been chasing ever since." },
      { id: "m_tw_6", text: "{leader} built the entire bout on the foundation of that opening hit." },
      { id: "m_tw_7", text: "The tachiai set the tone and the tone has never changed. {leader} has been in control throughout." },
      { id: "m_tw_8", text: "A perfect opening, and the scoreboard reflects it. {leader} never had to adjust." },
      { id: "m_tw_9", text: "{trailer} has been reactive all bout — a consequence of losing that first collision." },
    ],
  },

  injury: {
    sprain: [
      { id: "inj_spr_1", text: "A nasty sprain slows the rikishi down." },
      { id: "inj_spr_2", text: "Medical staff diagnoses a debilitating sprain." },
      { id: "inj_spr_3", text: "A twisted limb results in a severe sprain." },
      { id: "inj_spr_4", text: "A sharp movement causes a sudden sprain." },
      { id: "inj_spr_5", text: "The grimace says it all — a painful sprain to the joint." },
      { id: "inj_spr_6", text: "He lands awkwardly and the ankle gives. The crowd goes quiet." },
      { id: "inj_spr_7", text: "A sprain to the lower limb. Not career-ending, but the damage is done today." },
      { id: "inj_spr_8", text: "The ankle rolls on the tawara bales — an occupational hazard that has cost them dearly." },
      { id: "inj_spr_9", text: "The wrist bends the wrong way in the grapple. He walks off slowly, cradling the arm." },
      { id: "inj_spr_10", text: "A knee sprain in the drive. He finishes the bout on instinct alone." },
      { id: "inj_spr_11", text: "The sprain announces itself with a sharp inhale visible from the upper seats." },
      { id: "inj_spr_12", text: "He'll fight through it today. Tomorrow will be the honest accounting." },
    ],
    strain: [
      { id: "inj_str_1", text: "An overextension leads to a muscle strain." },
      { id: "inj_str_2", text: "The heavy lifting takes its toll with a deep strain." },
      { id: "inj_str_3", text: "A pulled muscle strains the rikishi's mobility." },
      { id: "inj_str_4", text: "The rikishi winces from a clear muscular strain." },
      { id: "inj_str_5", text: "A severe strain will require time off the dohyo." },
      { id: "inj_str_6", text: "Something pulls in the push — a strain that will linger." },
      { id: "inj_str_7", text: "The back seizes on the drive and the rikishi loses all power." },
      { id: "inj_str_8", text: "A hamstring strain mid-bout — he adjusts his stance immediately to compensate." },
      { id: "inj_str_9", text: "The pulling sensation in the lower back is unmistakable. The training staff will be busy tonight." },
      { id: "inj_str_10", text: "A muscle shouts a warning from somewhere in the shoulder. He heard it." },
      { id: "inj_str_11", text: "The strain is a quiet injury — invisible to the crowd but screaming to the rikishi." },
      { id: "inj_str_12", text: "Every bout in a basho adds to the toll. This strain is the bill coming due." },
    ],
    contusion: [
      { id: "inj_con_1", text: "A brutal impact leaves a deep contusion." },
      { id: "inj_con_2", text: "The rikishi sports a dark contusion from the collision." },
      { id: "inj_con_3", text: "A heavy blow results in a painful contusion." },
      { id: "inj_con_4", text: "Swelling and bruising mark a serious contusion." },
      { id: "inj_con_5", text: "The blunt force of the tachiai causes a contusion." },
      { id: "inj_con_6", text: "A deep bruise forms instantly where the blow landed." },
      { id: "inj_con_7", text: "The area swells immediately. It will be far worse in the morning." },
      { id: "inj_con_8", text: "The side of the ribcage took the impact. Breathing will be an adventure for a week." },
      { id: "inj_con_9", text: "A contusion to the thigh — the clay is an unforgiving surface to fall on." },
      { id: "inj_con_10", text: "The purple starts to show through the skin almost immediately. A fierce contusion." },
      { id: "inj_con_11", text: "He presses a hand to the bruised area once, grimaces, and says nothing to the medics." },
      { id: "inj_con_12", text: "The contusion is the cost of a tournament. He will wear it like a badge." },
    ],
    inflammation: [
      { id: "inj_inf_1", text: "Chronic inflammation flares up unexpectedly." },
      { id: "inj_inf_2", text: "Severe inflammation limits the joint's movement." },
      { id: "inj_inf_3", text: "The rikishi is sidelined by painful inflammation." },
      { id: "inj_inf_4", text: "Wear and tear results in acute inflammation." },
      { id: "inj_inf_5", text: "Medical reports cite severe localized inflammation." },
      { id: "inj_inf_6", text: "An old inflammation site flares under the tournament's strain." },
      { id: "inj_inf_7", text: "The knee swells visibly. The inflammation is not new — but it is severe." },
      { id: "inj_inf_8", text: "A tournament's worth of punishment has ignited the inflammation in that joint." },
      { id: "inj_inf_9", text: "The elbow has been quietly inflamed for days. Today it demanded to be heard." },
      { id: "inj_inf_10", text: "Chronic inflammation — managed, until it wasn't. The medics will drain it tonight." },
      { id: "inj_inf_11", text: "The soft tissue is angry. Rest is the prescription. Rest is the one thing a basho does not allow." },
      { id: "inj_inf_12", text: "Every rikishi carries inflammation through a tournament. Not all of them carry it gracefully." },
    ],
    tear: [
      { id: "inj_tea_1", text: "A devastating muscle tear stops the rikishi in their tracks." },
      { id: "inj_tea_2", text: "A loud pop signals a serious ligament tear." },
      { id: "inj_tea_3", text: "The diagnosis is grim: a full tear requiring surgery." },
      { id: "inj_tea_4", text: "A partial tear will keep the rikishi out for weeks." },
      { id: "inj_tea_5", text: "The sheer force of the throw causes a tissue tear." },
      { id: "inj_tea_6", text: "An audible pop. The arena falls silent. This is serious." },
      { id: "inj_tea_7", text: "The tear is complete. Medical staff move swiftly. Everyone knows what it means." },
      { id: "inj_tea_8", text: "The MCL gives way under the torsion of the throw. A career-altering moment." },
      { id: "inj_tea_9", text: "Nobody in the arena needed a diagnosis. That sound told the whole story." },
      { id: "inj_tea_10", text: "He sits on the clay and holds the knee. The crowd applauds in respectful silence." },
      { id: "inj_tea_11", text: "A rotator cuff tear on the belt pull — the arm simply gives out mid-technique." },
      { id: "inj_tea_12", text: "The months ahead will be about surgery, rehabilitation, and the slow reclamation of strength." },
    ],
    fracture: [
      { id: "inj_fra_1", text: "A sickening crack confirms a bone fracture." },
      { id: "inj_fra_2", text: "The rikishi suffers a structural fracture." },
      { id: "inj_fra_3", text: "A heavy fall results in a clean fracture." },
      { id: "inj_fra_4", text: "X-rays reveal a hairline fracture." },
      { id: "inj_fra_5", text: "A brutal collision leaves the rikishi with a fracture." },
      { id: "inj_fra_6", text: "The sound that follows the fall is one nobody in the hall wants to hear." },
      { id: "inj_fra_7", text: "A fracture. The kind that ends tournaments and tests careers." },
      { id: "inj_fra_8", text: "A stress fracture in the metatarsal — weeks of silently competing on a broken foot." },
      { id: "inj_fra_9", text: "The collarbone snaps on the impact with the clay. He does not get up quickly." },
      { id: "inj_fra_10", text: "A hairline fracture to the wrist — enough to render the grip useless." },
      { id: "inj_fra_11", text: "The bone gave before the muscle. That is the final verdict on this basho." },
      { id: "inj_fra_12", text: "He bows to the gyoji with the fractured arm held carefully at his side. The old codes demand it." },
    ],
    nerve: [
      { id: "inj_nrv_1", text: "A pinched nerve causes shooting pain down the limb." },
      { id: "inj_nrv_2", text: "Nerve damage leaves the rikishi with lingering numbness." },
      { id: "inj_nrv_3", text: "A jarring impact causes severe nerve irritation." },
      { id: "inj_nrv_4", text: "The rikishi loses grip strength due to a nerve issue." },
      { id: "inj_nrv_5", text: "A complex nerve injury complicates recovery." },
      { id: "inj_nrv_6", text: "The arm hangs differently. A nerve has been affected." },
      { id: "inj_nrv_7", text: "Numbness and weakness in the limb — a nerve injury that may take months." },
      { id: "inj_nrv_8", text: "The stinger down the arm comes during the tachiai. He shakes the hand, but the pins and needles persist." },
      { id: "inj_nrv_9", text: "A cervical nerve issue — the neck took a hit and the signals are misfiring." },
      { id: "inj_nrv_10", text: "The grip vanishes in an instant. Not fatigue — a nerve. The hand simply stopped working." },
      { id: "inj_nrv_11", text: "Nerve damage is the ghost injury. Invisible, unpredictable, and slow to heal." },
      { id: "inj_nrv_12", text: "He opens and closes the fist slowly, trying to reconnect the signals. The nerve is not cooperating." },
    ],
    unknown: [
      { id: "inj_unk_1",  text: "The rikishi goes down with an unspecified injury." },
      { id: "inj_unk_2",  text: "Medical staff is unsure of the exact nature of the injury." },
      { id: "inj_unk_3",  text: "A mysterious ailment sidelines the rikishi." },
      { id: "inj_unk_4",  text: "The injury details remain unclear at this time." },
      { id: "inj_unk_5",  text: "An undisclosed injury forces a withdrawal." },
      { id: "inj_unk_6",  text: "Something has gone wrong. The rikishi is down and the stable is silent." },
      { id: "inj_unk_7",  text: "Medics attend to the rikishi. No announcement is made. The arena waits." },
      { id: "inj_unk_8",  text: "He walked to the preparation room under his own power. That is all the stable will say." },
      { id: "inj_unk_9",  text: "The exact nature of the injury is being kept close. The retirement question hangs in the air." },
      { id: "inj_unk_10", text: "Something in the lower body. He left the dohyo with a limp that was not there this morning." },
      { id: "inj_unk_11", text: "An old site that was declared healed. Clearly it was not." },
      { id: "inj_unk_12", text: "The attending physician gives nothing away. The rikishi gives even less." },
    ],
  },

  institutional: {
    GOVERNANCE_STATUS_CHANGED: {
      default: [
        { id: "inst_gsc_1", text: "The JSA issues a formal notice: the heya's governance status has been officially revised." },
        { id: "inst_gsc_2", text: "An urgent dispatch from the council confirms a strict alteration in governance status." },
        { id: "inst_gsc_3", text: "In a stern ruling, the compliance committee mandates a new governance status." },
        { id: "inst_gsc_4", text: "The stablemaster accepts the board's decision to modify their institutional standing." },
        { id: "inst_gsc_5", text: "Following an internal review, the heya's governance status is publicly updated." },
      ],
      strict: [
        { id: "inst_gsc_1s", text: "A formal decree is issued. The stable's governance classification has been revised downward. No appeal process was offered." },
        { id: "inst_gsc_2s", text: "The compliance panel rules swiftly. The heya's status is changed and the Oyakata is given seventy-two hours to respond in writing." },
        { id: "inst_gsc_3s", text: "In language that leaves no room for ambiguity, the JSA updates the stable's governance standing." },
        { id: "inst_gsc_4s", text: "The Oyakata receives the ruling without visible emotion. The change in status is recorded and circulated." },
        { id: "inst_gsc_5s", text: "This governance revision carries monitoring conditions. The stable will operate under increased scrutiny." },
      ],
      indulgent: [
        { id: "inst_gsc_1i", text: "The governance committee updates the stable's standing with a note of encouragement attached to the formal letter." },
        { id: "inst_gsc_2i", text: "A revised status comes with a lenient timeline for compliance. The JSA seems willing to work with the stable." },
        { id: "inst_gsc_3i", text: "The Oyakata is briefed informally before the official notice arrives. The change is framed as an opportunity." },
        { id: "inst_gsc_4i", text: "The governance update is gentle in tone. The committee stresses that this is guidance, not punishment." },
        { id: "inst_gsc_5i", text: "A symbolic reclassification. The committee wanted it on record. The practical consequences are minimal." },
      ],
      traditionalist: [
        { id: "inst_gsc_1t", text: "The elders have deliberated and the decision is clear. The governance of this heya has been found lacking in the ancient standards." },
        { id: "inst_gsc_2t", text: "A governance revision rooted in tradition — the committee cites precedents reaching back three decades." },
        { id: "inst_gsc_3t", text: "The old men of the council have spoken. The status change is announced with ceremony and gravitas." },
        { id: "inst_gsc_4t", text: "The way of the heya has not honored the way of the sport. The governance status reflects that judgment." },
        { id: "inst_gsc_5t", text: "The committee reminds the stable that governance is not bureaucracy — it is the living expression of sumo's values." },
      ],
      scientist: [
        { id: "inst_gsc_1sc", text: "A data-driven governance review concludes. The status is revised based on quantified compliance metrics." },
        { id: "inst_gsc_2sc", text: "The committee's report runs to fourteen pages. The governance status change is the outcome of rigorous analysis." },
        { id: "inst_gsc_3sc", text: "The new governance classification reflects an objective assessment of the stable's institutional performance indicators." },
        { id: "inst_gsc_4sc", text: "The Oyakata reviews the spreadsheet of compliance benchmarks. The status change was statistically inevitable." },
        { id: "inst_gsc_5sc", text: "A methodical review yields a methodical outcome. The governance status is updated accordingly." },
      ],
      gambler: [
        { id: "inst_gsc_1g", text: "The governance vote was closer than expected. The Oyakata's bet on leniency didn't quite pay off." },
        { id: "inst_gsc_2g", text: "A governance status change that the stable had been banking against. The odds had shifted against them." },
        { id: "inst_gsc_3g", text: "The JSA has called in a debt. The governance classification changes, and the stable must cover it." },
        { id: "inst_gsc_4g", text: "The ruling came down to a single council vote. The Oyakata lost the coin flip that matters." },
        { id: "inst_gsc_5g", text: "A risky governance posture has yielded consequences. The status changes and the chips are down." },
      ],
      nurturer: [
        { id: "inst_gsc_1n", text: "The governance change is communicated with care — the JSA wants the stable to improve, not to suffer." },
        { id: "inst_gsc_2n", text: "The updated status comes with a support package. The committee believes in this heya's potential." },
        { id: "inst_gsc_3n", text: "The Oyakata takes the governance revision to heart. It is received as a call to do better for the rikishi." },
        { id: "inst_gsc_4n", text: "A gentle but firm reclassification. The JSA reaches out to the stable with a mentoring offer." },
        { id: "inst_gsc_5n", text: "The governance status changes. The committee adds: 'We are here to help you through this transition.'" },
      ],
      tyrant: [
        { id: "inst_gsc_1ty", text: "The governance status changes. The Oyakata does not acknowledge the notice publicly. Inside the stable, it is a different story." },
        { id: "inst_gsc_2ty", text: "The JSA revises the heya's status. Inside, the anger from the Oyakata is reportedly volcanic." },
        { id: "inst_gsc_3ty", text: "A governance reclassification that the Oyakata views as an attack. The rikishi brace for the aftermath." },
        { id: "inst_gsc_4ty", text: "The status change is filed away. The Oyakata begins strategizing for reprisal through unofficial channels." },
        { id: "inst_gsc_5ty", text: "The ruling from the JSA is firm. The ruling from the Oyakata to the rikishi that evening is firmer still." },
      ],
      strategist: [
        { id: "inst_gsc_1st", text: "The governance change was anticipated. The stable had already prepared its response before the notice arrived." },
        { id: "inst_gsc_2st", text: "A calculated adaptation to the new governance status. The Oyakata moves pieces that nobody else can see yet." },
        { id: "inst_gsc_3st", text: "The JSA changes the classification. The Oyakata changes the approach. Both acts are deliberate." },
        { id: "inst_gsc_4st", text: "The governance revision is absorbed and analyzed. The stable will use this as leverage in the next review cycle." },
        { id: "inst_gsc_5st", text: "The Oyakata had gamed out this scenario months ago. The updated status fits neatly into the long-term plan." },
      ],
    },
    GOVERNANCE_RULING: {
      default: [
        { id: "inst_gov_1", text: "The elders hand down a severe governance ruling, demanding immediate compliance." },
        { id: "inst_gov_2", text: "A compassionate but firm governance ruling is issued by the committee to guide the heya." },
        { id: "inst_gov_3", text: "The board's governance ruling sends a clear message about institutional integrity." },
        { id: "inst_gov_4", text: "An unprecedented governance ruling alters the future trajectory of the stable." },
        { id: "inst_gov_5", text: "The disciplinary panel announces a final, binding governance ruling." },
      ],
      strict: [
        { id: "inst_gov_1s", text: "The ruling is unambiguous and immediate. The stable is given no latitude on timeline or interpretation." },
        { id: "inst_gov_2s", text: "A governance ruling with real teeth. Non-compliance carries automatic escalation to the full council." },
        { id: "inst_gov_3s", text: "The disciplinary panel delivers a strict ruling. There is no softening language in the document." },
        { id: "inst_gov_4s", text: "The Oyakata is summoned to read the ruling in person. The panel did not want any ambiguity about its severity." },
        { id: "inst_gov_5s", text: "A binding governance mandate. The committee has been watching this heya for some time. They will continue to watch." },
      ],
      indulgent: [
        { id: "inst_gov_1i", text: "The governance ruling is framed as constructive feedback. The tone is collegial, the consequences modest." },
        { id: "inst_gov_2i", text: "The panel issues a ruling but leaves significant room for interpretation. The stable is given breathing space." },
        { id: "inst_gov_3i", text: "A lenient governance decision. The committee wanted a ruling on record but stopped short of real sanctions." },
        { id: "inst_gov_4i", text: "The ruling comes with a generous compliance window. The committee seems reluctant to push too hard." },
        { id: "inst_gov_5i", text: "The Oyakata nods, accepts the ruling graciously, and privately calculates how little needs to change." },
      ],
      traditionalist: [
        { id: "inst_gov_1t", text: "The ruling invokes the heritage of the heya system. Governance is framed as a sacred obligation." },
        { id: "inst_gov_2t", text: "The committee's ruling is drawn from old precedent. The older members cite bouts from decades past to make their point." },
        { id: "inst_gov_3t", text: "Tradition demands discipline. The governance ruling is delivered with all the formality the occasion deserves." },
        { id: "inst_gov_4t", text: "A ruling rooted in the old ways. The panel chair reminds the stable that sumo's governance has centuries of wisdom behind it." },
        { id: "inst_gov_5t", text: "The ruling is given. The elders expect it to be honored not because of the paperwork, but because it is right." },
      ],
      scientist: [
        { id: "inst_gov_1sc", text: "The governance ruling follows a structured review of performance data and compliance metrics." },
        { id: "inst_gov_2sc", text: "A decision tree was followed. The ruling is the outcome at the bottom of it. No more, no less." },
        { id: "inst_gov_3sc", text: "The panel's findings are documented with clinical precision. The ruling is reproducible and evidence-based." },
        { id: "inst_gov_4sc", text: "Objections were raised and weighed against the data. The ruling stands as the statistically supported conclusion." },
        { id: "inst_gov_5sc", text: "The committee chair presents the ruling as a hypothesis confirmed by the stable's own operational record." },
      ],
      gambler: [
        { id: "inst_gov_1g", text: "The ruling goes against the stable. The Oyakata had hedged their bets on a different outcome." },
        { id: "inst_gov_2g", text: "A high-stakes governance ruling. The stable's behavior was a bet — and the JSA just called it." },
        { id: "inst_gov_3g", text: "The Oyakata had played the odds. The committee's ruling shows the house still wins." },
        { id: "inst_gov_4g", text: "An unexpected governance verdict. The Oyakata reads the ruling twice, recalculating." },
        { id: "inst_gov_5g", text: "The panel ruled against the stable. A calculated risk that failed to pay out." },
      ],
      nurturer: [
        { id: "inst_gov_1n", text: "The ruling is delivered with warmth. The committee wants the stable to succeed — they are invested in the outcome." },
        { id: "inst_gov_2n", text: "The governance ruling comes with an offer of mediation and ongoing support. The JSA wants resolution, not punishment." },
        { id: "inst_gov_3n", text: "A firm ruling, but not an unkind one. The panel chair spoke to the Oyakata privately before the formal notice." },
        { id: "inst_gov_4n", text: "The committee's goal is the welfare of the rikishi. The governance ruling serves that goal, and it is explained as such." },
        { id: "inst_gov_5n", text: "A ruling designed to correct, not to wound. The committee genuinely believes the stable can grow from this." },
      ],
      tyrant: [
        { id: "inst_gov_1ty", text: "The ruling is received in silence. Inside the stable walls that evening, the silence ends." },
        { id: "inst_gov_2ty", text: "A governance ruling against the Oyakata's wishes. The rikishi brace for the mood that follows." },
        { id: "inst_gov_3ty", text: "The Oyakata publicly accepts the ruling. Nobody inside the stable believes it." },
        { id: "inst_gov_4ty", text: "The JSA hands down its ruling. The Oyakata responds with a controlled fury that frightens the junior members." },
        { id: "inst_gov_5ty", text: "A ruling delivered by the committee. A separate, unwritten ruling handed down in the stable hours later." },
      ],
      strategist: [
        { id: "inst_gov_1st", text: "The ruling was expected. The stable's response was prepared weeks in advance." },
        { id: "inst_gov_2st", text: "A governance ruling that the Oyakata will incorporate into the next quarter's strategy review." },
        { id: "inst_gov_3st", text: "The Oyakata treats the ruling as information. Everything is information. Everything can be used." },
        { id: "inst_gov_4st", text: "The stable accepts the ruling on record while quietly restructuring to make the ruling irrelevant within six months." },
        { id: "inst_gov_5st", text: "A ruling absorbed with the calm of a person who had already played out this scenario. The counter-move is already in motion." },
      ],
    },
    WELFARE_ALERT: {
      default: [
        { id: "inst_wel_1", text: "A critical welfare alert is triggered, prompting an immediate investigation by the JSA." },
        { id: "inst_wel_2", text: "The welfare committee raises a red flag regarding conditions at the heya." },
        { id: "inst_wel_3", text: "A formal welfare alert underscores deep concerns for the rikishi's wellbeing." },
        { id: "inst_wel_4", text: "The stablemaster is summoned following a serious welfare alert." },
        { id: "inst_wel_5", text: "Welfare monitors issue a stern warning detailing unacceptable conditions." },
      ],
      strict: [
        { id: "inst_wel_1s", text: "The welfare alert triggers automatic escalation. Inspectors are dispatched same day." },
        { id: "inst_wel_2s", text: "A formal welfare notice is issued. The JSA will not wait for a response before sending investigators." },
        { id: "inst_wel_3s", text: "Unacceptable conditions. The committee's language is not diplomatic — it is urgent." },
        { id: "inst_wel_4s", text: "The Oyakata is summoned to appear before the panel within forty-eight hours." },
        { id: "inst_wel_5s", text: "A welfare alert with suspension language attached. The committee means business." },
      ],
      indulgent: [
        { id: "inst_wel_1i", text: "A welfare advisory is issued — softer in tone than a formal alert, but the concern is real." },
        { id: "inst_wel_2i", text: "The committee raises a welfare flag. The Oyakata is given ample time to address the findings informally." },
        { id: "inst_wel_3i", text: "A welfare concern is noted. The panel recommends improvements without issuing a formal sanction." },
        { id: "inst_wel_4i", text: "The welfare note is gentle. The committee prefers to encourage improvement over issuing penalties." },
        { id: "inst_wel_5i", text: "A welfare observation rather than an alert. The committee wants to give the stable the benefit of the doubt." },
      ],
      traditionalist: [
        { id: "inst_wel_1t", text: "The welfare of the rikishi is sacred. The committee acts on this alert with the full weight of sumo's traditions." },
        { id: "inst_wel_2t", text: "A welfare alert that speaks to the oldest obligation in the heya system — a master's duty to their fighters." },
        { id: "inst_wel_3t", text: "The elders are troubled. Sumo has always demanded hardship, but never cruelty. This alert tests that line." },
        { id: "inst_wel_4t", text: "The welfare of the men under that roof has been compromised. The committee invokes its oldest mandate." },
        { id: "inst_wel_5t", text: "The code of the oyakata demands the protection of the rikishi. The welfare alert says that code was broken." },
      ],
      scientist: [
        { id: "inst_wel_1sc", text: "Welfare metrics fell below the committee's established threshold. The alert is data-confirmed." },
        { id: "inst_wel_2sc", text: "A welfare alert generated by the monitoring system's quantitative review of stable conditions." },
        { id: "inst_wel_3sc", text: "The analysis is clear. Conditions at the heya do not meet documented welfare standards. The alert is issued accordingly." },
        { id: "inst_wel_4sc", text: "The committee's welfare dashboard flagged multiple indicators simultaneously. An investigation is the prescribed response." },
        { id: "inst_wel_5sc", text: "Three separate welfare metrics breached acceptable ranges. The alert is the logical outcome." },
      ],
      gambler: [
        { id: "inst_wel_1g", text: "The Oyakata bet that the welfare situation would stay quiet. The alert proves otherwise." },
        { id: "inst_wel_2g", text: "A welfare alert the stable hoped would never come. The odds didn't hold." },
        { id: "inst_wel_3g", text: "The committee has found out. The stable's luck in keeping things internal has run out." },
        { id: "inst_wel_4g", text: "The welfare bet didn't pay off. The JSA holds the hand now." },
        { id: "inst_wel_5g", text: "A welfare alert that represents a miscalculation — someone thought the conditions were acceptable enough to risk." },
      ],
      nurturer: [
        { id: "inst_wel_1n", text: "The welfare alert visibly shakes the Oyakata, who is genuinely distressed that conditions fell short of the care owed to their rikishi." },
        { id: "inst_wel_2n", text: "A welfare flag that prompts real soul-searching in the stable. The Oyakata takes it personally." },
        { id: "inst_wel_3n", text: "The alert lands hard in a stable that prides itself on caring for its rikishi. The Oyakata begins addressing it immediately." },
        { id: "inst_wel_4n", text: "The Oyakata meets with every rikishi individually before the JSA investigators arrive. They want to understand what happened." },
        { id: "inst_wel_5n", text: "A welfare alert treated not as a bureaucratic crisis, but as a genuine failure that demands reflection and repair." },
      ],
      tyrant: [
        { id: "inst_wel_1ty", text: "Welfare investigators force their way into the stable after reports from three separate rikishi. The Oyakata refuses to acknowledge the findings." },
        { id: "inst_wel_2ty", text: "A welfare alert. Inside the stable, the Oyakata demands to know who spoke to the committee." },
        { id: "inst_wel_3ty", text: "The welfare flag has been raised. The rikishi who raised it is no longer training at the front of the group." },
        { id: "inst_wel_4ty", text: "The JSA welfare alert names specific incidents. The Oyakata disputes each one in writing." },
        { id: "inst_wel_5ty", text: "A welfare investigation begins. The Oyakata's cooperation is technically present and functionally absent." },
      ],
      strategist: [
        { id: "inst_wel_1st", text: "The welfare alert was anticipated. Remediation began quietly before the committee's inspectors were appointed." },
        { id: "inst_wel_2st", text: "A welfare flag that the stable absorbs, addresses, and turns into a compliance showcase for the next review." },
        { id: "inst_wel_3st", text: "The Oyakata had considered the welfare risk. The response protocol was already written." },
        { id: "inst_wel_4st", text: "The alert is met with careful documentation and proactive outreach. The stable intends to come out of this looking exemplary." },
        { id: "inst_wel_5st", text: "A welfare alert used as an opportunity. The Oyakata is nothing if not adaptable." },
      ],
    },
  },

  finish: {
    normal: [
      { id: "f_n_1",  text: "{winner} finishes it — {kimarite}!" },
      { id: "f_n_2",  text: "That's it! {winner} takes the bout by {kimarite}!", tags: ["crowd_roar"] },
      { id: "f_n_3",  text: "{winner} seals the deal — {kimarite}!" },
      { id: "f_n_4",  text: "A definitive finish! {winner} executes a perfect {kimarite}." },
      { id: "f_n_5",  text: "{winner} drives the advantage home, winning with {kimarite}!" },
      { id: "f_n_6",  text: "There's the climax — {winner} wins via {kimarite}!" },
      { id: "f_n_7",  text: "{loser} has no answer for the {kimarite} from {winner}!" },
      { id: "f_n_8",  text: "A textbook application of {kimarite} gives {winner} the victory!" },
      { id: "f_n_9",  text: "{winner} muscles {loser} over the edge with a powerful {kimarite}!" },
      { id: "f_n_10", text: "No escape for {loser}! {winner} ends it via {kimarite}." },
      { id: "f_n_11", text: "A brilliant {kimarite} execution from {winner} to secure the win!" },
      { id: "f_n_12", text: "{winner} powers through the defense, concluding with {kimarite}!" },
      { id: "f_n_13", text: "The bout concludes as {winner} forcefully delivers a {kimarite}." },
      { id: "f_n_14", text: "{winner} has done it. {kimarite}. The gyoji's fan points clearly." },
      { id: "f_n_15", text: "Clean and decisive — {winner} finishes with {kimarite} and there is no doubt." },
      { id: "f_n_16", text: "The win was built on patience. The finish was {kimarite}. Classic." },
      { id: "f_n_17", text: "{loser} is out! {winner} gets the decision — {kimarite}." },
      { id: "f_n_18", text: "{winner} completes the job with {kimarite}. A professional performance." },
      { id: "f_n_19", text: "The gyoji calls it. {winner} via {kimarite}. No argument from the judges." },
      { id: "f_n_20", text: "{winner} steers {loser} to the boundary and the {kimarite} does the rest." },
      { id: "f_n_21", text: "An absolute masterclass! {winner} ends the struggle with a breathtaking {kimarite}." },
      { id: "f_n_22", text: "{winner} channels every ounce of power into a devastating {kimarite} to seal the match." },
      { id: "f_n_23", text: "The technique is undeniable! {winner} completes the {kimarite} as the gyoji points the fan." },
      { id: "f_n_24", text: "Not a single wasted movement from {winner}. The {kimarite} is the payoff for perfect technique." },
      { id: "f_n_25", text: "The shimpan will not be needed. That was {kimarite}, clean as anything." },
      { id: "f_n_26", text: "{winner} lands the winning technique and takes a small step back. The work is done." },
      { id: "f_n_27", text: "A decisive, unambiguous victory for {winner}. {kimarite}. The tournament continues." },
      { id: "f_n_28", text: "The {kimarite} was always coming once {winner} had established that position." },
      { id: "f_n_29", text: "{winner} relentlessly drives {loser} to the clay with {kimarite}!" },
      { id: "f_n_30", text: "A spectacular display of {kimarite}! {winner} claims the victory." },
      { id: "f_n_31", text: "The arena echoes with cheers as {winner} secures the win via {kimarite}." },
      { id: "f_n_32", text: "No escape for {loser}! {winner} executes a picture-perfect {kimarite}." },
      { id: "f_n_33", text: "{winner} forces the issue, ending the bout definitively with {kimarite}." },
      { id: "f_n_34", text: "A masterful transition into {kimarite} gives {winner} the nod." },
      { id: "f_n_35", text: "With overwhelming pressure, {winner} seals the match with {kimarite}." },
      { id: "f_n_36", text: "The power differential was clear. {winner} wins by {kimarite}." },
      { id: "f_n_37", text: "An elegant {kimarite} finish from {winner} leaves no room for debate." },
      { id: "f_n_38", text: "A swift and devastating {kimarite} — {winner} stands tall!" },
    ],
    upset: [
      { id: "f_u_1",  text: "UPSET! {winner} shocks the arena with {kimarite}!", tags: ["upset", "crowd_roar"] },
      { id: "f_u_2",  text: "A stunner — {winner} steals it by {kimarite}!", tags: ["upset"] },
      { id: "f_u_3",  text: "Unbelievable! {winner} pulls off a massive upset with {kimarite}!", tags: ["upset"] },
      { id: "f_u_4",  text: "The crowd goes wild! An unexpected {kimarite} win for {winner}!", tags: ["upset", "crowd_roar"] },
      { id: "f_u_5",  text: "Against all odds, {winner} conquers {loser} by {kimarite}!", tags: ["upset"] },
      { id: "f_u_6",  text: "A gigantic upset! {winner} catches {loser} with {kimarite}.", tags: ["upset"] },
      { id: "f_u_7",  text: "Nobody saw that coming — {winner} uses {kimarite} to score the huge win!", tags: ["upset"] },
      { id: "f_u_8",  text: "A breathtaking upset! {winner} brings down the giant with {kimarite}!", tags: ["upset", "crowd_roar"] },
      { id: "f_u_9",  text: "{loser} looks stunned! {winner} snatches victory via {kimarite}!", tags: ["upset"] },
      { id: "f_u_10", text: "Defying all expectations, {winner} pulls out a {kimarite} win!", tags: ["upset"] },
      { id: "f_u_11", text: "A David vs. Goliath moment! {winner} achieves the impossible with {kimarite}!", tags: ["upset"] },
      { id: "f_u_12", text: "The arena is in shock! {winner} drops {loser} with a sudden {kimarite}!", tags: ["upset", "gasps"] },
      { id: "f_u_13", text: "Cushions in the air! {winner} topples the favourite with {kimarite}!", tags: ["upset", "crowd_roar"] },
      { id: "f_u_14", text: "A seismic result! Nobody in the Kokugikan believed this was possible.", tags: ["upset"] },
      { id: "f_u_15", text: "{winner} will remember this forever. {kimarite}. The upset is complete.", tags: ["upset"] },
      { id: "f_u_16", text: "The scoreboard does not lie. The crowd does not believe the scoreboard.", tags: ["upset"] },
      { id: "f_u_17", text: "A name that will be spoken in this arena for years. {winner} with {kimarite}.", tags: ["upset"] },
      { id: "f_u_18", text: "The ranking system has been defied. {winner} over {loser}. Print it.", tags: ["upset", "crowd_roar"] },
      { id: "f_u_19", text: "Reporters are already rewriting their match reports. {winner} via {kimarite}. Nobody predicted this.", tags: ["upset"] },
      { id: "f_u_20", text: "{loser} stands at the edge of the dohyo and stares at the clay. That was supposed to be straightforward.", tags: ["upset"] },
    ],
    close_call: [
      { id: "f_c_1",  text: "So close at the edge — but {winner} gets it by {kimarite}!", tags: ["close_call", "gasps"] },
      { id: "f_c_2",  text: "A razor-thin finish! {winner} wins with {kimarite}!", tags: ["close_call"] },
      { id: "f_c_3",  text: "It goes down to the wire, but {winner} manages a {kimarite}!", tags: ["close_call"] },
      { id: "f_c_4",  text: "A breathless conclusion! {winner} barely pulls out the {kimarite}!", tags: ["close_call", "gasps"] },
      { id: "f_c_5",  text: "The gyoji almost had to call a mono-ii, but {winner}'s {kimarite} was clean!", tags: ["close_call"] },
      { id: "f_c_6",  text: "Narrowly escaping defeat, {winner} counters with {kimarite}!", tags: ["close_call"] },
      { id: "f_c_7",  text: "A hair's breadth away from a loss, {winner} secures the {kimarite}.", tags: ["close_call"] },
      { id: "f_c_8",  text: "The judges huddle. After a tense mono-ii, the {kimarite} is confirmed for {winner}.", tags: ["close_call", "mono_ii"] },
      { id: "f_c_9",  text: "That had to go to review — but the decision stands. {winner}, {kimarite}.", tags: ["close_call"] },
      { id: "f_c_10", text: "Both men seemed to touch down simultaneously, but {winner} is awarded the {kimarite}.", tags: ["close_call", "gasps"] },
      { id: "f_c_11", text: "The shimpan consult at length. The arena waits. The verdict: {winner} by {kimarite}.", tags: ["close_call", "mono_ii"] },
      { id: "f_c_12", text: "A finish so close the gyoji paused before pointing. {winner}. {kimarite}.", tags: ["close_call"] },
      { id: "f_c_13", text: "Toenail sumo. {winner} was out by less than the width of a straw bale — but out first.", tags: ["close_call", "gasps"] },
      { id: "f_c_14", text: "The slowest of slow-motion replays will decide this one. {winner} survives the review.", tags: ["close_call"] },
    ],
    kinboshi: [
      { id: "f_k_1",  text: "KINBOSHI! {winner} claims a gold star with {kimarite}!", tags: ["kinboshi", "crowd_roar"] },
      { id: "f_k_2",  text: "A gold star victory! {winner} defeats a Yokozuna by {kimarite}!", tags: ["kinboshi"] },
      { id: "f_k_3",  text: "The Yokozuna falls! {winner} earns a kinboshi via {kimarite}!", tags: ["kinboshi"] },
      { id: "f_k_4",  text: "History is made! {winner} topples the champion with {kimarite}.", tags: ["kinboshi"] },
      { id: "f_k_5",  text: "A legendary moment as {winner} secures a kinboshi with {kimarite}!", tags: ["kinboshi"] },
      { id: "f_k_6",  text: "The grand champion goes down! KINBOSHI for {winner} by {kimarite}!", tags: ["kinboshi", "crowd_roar"] },
      { id: "f_k_7",  text: "A brilliant performance yields a gold star! {winner} wins by {kimarite}!", tags: ["kinboshi"] },
      { id: "f_k_8",  text: "The zabuton rain begins! A kinboshi for {winner}! The Yokozuna has fallen!", tags: ["kinboshi", "crowd_roar"] },
      { id: "f_k_9",  text: "{winner} will wear that gold star proudly. {kimarite}. The Yokozuna had no answer.", tags: ["kinboshi"] },
      { id: "f_k_10", text: "A moment that will echo through every tournament record. Kinboshi — {winner} over the Yokozuna.", tags: ["kinboshi"] },
      { id: "f_k_11", text: "The impossible. {winner} drops the Yokozuna by {kimarite}. The Kokugikan detonates.", tags: ["kinboshi", "crowd_roar"] },
      { id: "f_k_12", text: "A gold star is born. {winner} executed {kimarite} on a Yokozuna and never wavered.", tags: ["kinboshi"] },
      { id: "f_k_13", text: "The Yokozuna bows. {winner} bows deeper. But the outcome is undeniable — kinboshi.", tags: ["kinboshi"] },
      { id: "f_k_14", text: "Generations of rikishi dream of this moment. {winner} has just lived it.", tags: ["kinboshi", "crowd_roar"] },
      { id: "f_k_15", text: "Every zabuton in the building seems to be in the air. {winner}. Kinboshi. The sport will discuss this for years.", tags: ["kinboshi", "crowd_roar"] },
    ],
  },

  tactical: {
    oshi_strategy: [
      { id: "tac_oshi_1", text: "📋 {leader}'s game plan: deny the belt, full forward pressure." },
      { id: "tac_oshi_2", text: "📋 {leader} comes in with a clear oshi strategy — no belt wrestling today." },
      { id: "tac_oshi_3", text: "📋 The commentators note {leader} is set up for relentless pushing." },
      { id: "tac_oshi_4", text: "📋 {leader} wants to keep both hands on {trailer}'s chest — pure oshi." },
      { id: "tac_oshi_5", text: "📋 Forward pressure is the order of the day for {leader}." },
      { id: "tac_oshi_6", text: "📋 No mawashi, no problem. {leader} has all the tools to win with thrusts alone." },
      { id: "tac_oshi_7", text: "📋 {leader} will stay tall and thrust. Don't expect any belt grabbing." },
      { id: "tac_oshi_8", text: "📋 The plan from {leader}'s camp: keep it on the outside, keep it moving forward." },
      { id: "tac_oshi_9", text: "📋 {leader} trusts the tsuppari completely. The belt is irrelevant to this game plan." },
      { id: "tac_oshi_10", text: "📋 An oshi specialist in full preparation mode. {leader} wants a short, decisive bout." },
    ],
    yotsu_strategy: [
      { id: "tac_yotsu_1", text: "📋 {leader}'s approach: get to the belt at all costs." },
      { id: "tac_yotsu_2", text: "📋 {leader} wants this on the mawashi — a patient belt-hunting plan." },
      { id: "tac_yotsu_3", text: "📋 Classic yotsu preparation from {leader} — absorb and grapple." },
      { id: "tac_yotsu_4", text: "📋 {leader} aims to establish migi-yotsu early — right hand inside." },
      { id: "tac_yotsu_5", text: "📋 The commentators see {leader} adjusting the mawashi — belt sumo on the menu." },
      { id: "tac_yotsu_6", text: "📋 {leader} is a grappler at heart. Get to the belt, drive, win." },
      { id: "tac_yotsu_7", text: "📋 The inside position is everything for {leader}. That's where this bout gets decided." },
      { id: "tac_yotsu_8", text: "📋 {leader} will absorb the initial charge and look to wrap up immediately." },
      { id: "tac_yotsu_9", text: "📋 Belt sumo is {leader}'s church. The mawashi is the altar. Everything flows from the grip." },
      { id: "tac_yotsu_10", text: "📋 {leader} has drilled the grip entry for weeks. The tachiai will immediately become a belt fight." },
    ],
    speedster_strategy: [
      { id: "tac_speed_1", text: "📋 {leader} will use footwork — movement sumo is the plan." },
      { id: "tac_speed_2", text: "📋 Quick feet, sharp angles — {leader} aims to stay mobile." },
      { id: "tac_speed_3", text: "📋 The commentators say {leader} will rely on lateral movement today." },
      { id: "tac_speed_4", text: "📋 {leader}'s game: don't stand still, don't let {trailer} square up." },
      { id: "tac_speed_5", text: "📋 Speed kills — {leader} plans to make {trailer} chase." },
      { id: "tac_speed_6", text: "📋 {leader} will circle, probe, and attack from unexpected angles." },
      { id: "tac_speed_7", text: "📋 If {leader} can stay on the move, {trailer}'s size advantage vanishes." },
      { id: "tac_speed_8", text: "📋 {leader} doesn't need to win a strength contest — just a footwork contest." },
      { id: "tac_speed_9", text: "📋 The strategy is all lateral movement. Keep {trailer} turning, keep {trailer} guessing." },
      { id: "tac_speed_10", text: "📋 {leader} intends to be somewhere else every time {trailer} commits." },
    ],
    adaptive_strategy: [
      { id: "tac_ada_1", text: "📋 {leader} is playing it smart, adjusting to {trailer}'s every move." },
      { id: "tac_ada_2", text: "📋 High-IQ sumo from {leader} — a masterclass in adaptation." },
      { id: "tac_ada_3", text: "📋 {leader} has no fixed plan. The plan is to read and react." },
      { id: "tac_ada_4", text: "📋 Versatile and unpredictable — {leader} gives opponents no pattern to exploit." },
      { id: "tac_ada_5", text: "📋 {leader} will start with oshi and shift to yotsu if the opening appears." },
      { id: "tac_ada_6", text: "📋 The preparation room couldn't give {leader} a fixed game plan. They have too many options." },
      { id: "tac_ada_7", text: "📋 The opponent has a style. {leader} has ten responses to it. That's the difference." },
      { id: "tac_ada_8", text: "📋 {leader} will read the first two seconds and decide everything from there." },
    ],
    blitzer_fatigue: [
      { id: "tac_blz_1", text: "📋 The high-octane start takes its toll — {leader} is slowing down." },
      { id: "tac_blz_2", text: "📋 {leader}'s explosive energy is waning... can they finish?" },
      { id: "tac_blz_3", text: "📋 The blitz strategy only works if the bout ends early. It hasn't." },
      { id: "tac_blz_4", text: "📋 {leader} burned hard out of the gate. The question now is reserves." },
      { id: "tac_blz_5", text: "📋 The tank is nearly empty for {leader}. The burst has become a plod." },
      { id: "tac_blz_6", text: "📋 {leader}'s opening sixty seconds were spectacular. This second minute is a different story." },
      { id: "tac_blz_7", text: "📋 Blitzer sumo only works when it ends fast. {leader} needed this to be over already." },
      { id: "tac_blz_8", text: "📋 The commentators warned about {leader}'s fitness for a long bout. They were not wrong." },
    ],
    mountain_resilience: [
      { id: "tac_mtn_1", text: "📋 {leader} is an immovable object — absorbing everything {trailer} throws." },
      { id: "tac_mtn_2", text: "📋 Like a mountain, {leader} stands firm against the assault." },
      { id: "tac_mtn_3", text: "📋 The bigger they are, the longer the bout can last. {leader} counts on it." },
      { id: "tac_mtn_4", text: "📋 {leader}'s strategy is simple: take the hits, stay upright, and wait." },
      { id: "tac_mtn_5", text: "📋 {leader} is a boulder. {trailer} is being asked to move a boulder." },
      { id: "tac_mtn_6", text: "📋 The mountain philosophy: let the attacker exhaust themselves. Then act." },
      { id: "tac_mtn_7", text: "📋 {leader} has been standing up to charges like this for a decade. This is familiar territory." },
      { id: "tac_mtn_8", text: "📋 The mass advantage of {leader} makes every forward push a geometry problem for {trailer}." },
    ],
    stalwart_counter: [
      { id: "tac_stw_1", text: "📋 {leader} is waiting for the mistake, coiled and ready to counter." },
      { id: "tac_stw_2", text: "📋 A defensive masterclass from {leader} — the counter-attack is coming." },
      { id: "tac_stw_3", text: "📋 {leader} gives ground deliberately. The trap will be sprung when the time is right." },
      { id: "tac_stw_4", text: "📋 Patience is the weapon. {leader} needs {trailer} to overcommit once." },
      { id: "tac_stw_5", text: "📋 Every retreat from {leader} is bait. {trailer} should not be chasing." },
      { id: "tac_stw_6", text: "📋 {leader} can win from the edge. They have done it before." },
      { id: "tac_stw_7", text: "📋 The counter-attacking style requires near-perfect timing. {leader} lives for that pressure." },
      { id: "tac_stw_8", text: "📋 The commentators call it reactive sumo. {leader} calls it a trap." },
    ],
    trickster_agility: [
      { id: "tac_tri_1", text: "📋 {leader} is all smoke and mirrors — confusing {trailer} with lateral bursts." },
      { id: "tac_tri_2", text: "📋 Trickery and speed — {leader} is dissecting the opponent's balance." },
      { id: "tac_tri_3", text: "📋 {leader} will feint, pull, and redirect. {trailer} must not chase." },
      { id: "tac_tri_4", text: "📋 Unconventional is {leader}'s game. Expect the unexpected at every turn." },
      { id: "tac_tri_5", text: "📋 {leader} studies a move, shows it, and then does something completely different." },
      { id: "tac_tri_6", text: "📋 The harite isn't the attack — it's the setup. {leader} plays two moves ahead." },
      { id: "tac_tri_7", text: "📋 A slippery tactician. {trailer} will need to be disciplined or they'll be chasing shadows." },
      { id: "tac_tri_8", text: "📋 {leader} doesn't win with power. They win by making power look ridiculous." },
    ],
  },

  connective: {
    short: [
      { id: "conn_1",  text: "Meanwhile…" },
      { id: "conn_2",  text: "Back on the clay…" },
      { id: "conn_3",  text: "The battle rages on…" },
      { id: "conn_4",  text: "And still they fight…" },
      { id: "conn_5",  text: "Neither man yields…" },
      { id: "conn_6",  text: "The dohyo demands more…" },
      { id: "conn_7",  text: "Seconds feel like minutes inside that ring…" },
      { id: "conn_8",  text: "The gyoji watches. The crowd watches. Nobody breathes." },
      { id: "conn_9",  text: "On the clay…" },
      { id: "conn_10", text: "Time stretches in the Kokugikan…" },
      { id: "conn_11", text: "They reset. The tension does not." },
      { id: "conn_12", text: "A moment of stillness before the next storm." },
      { id: "conn_13", text: "Neither willing to concede an inch…" },
      { id: "conn_14", text: "The bout goes on…" },
      { id: "conn_15", text: "Breathing hard. Still standing." },
      { id: "conn_16", text: "The dohyo gives nothing. The men give everything." },
      { id: "conn_17", text: "A pause. A breath. Then back to war." },
      { id: "conn_18", text: "The gyoji steps half a pace closer." },
      { id: "conn_19", text: "The crowd has gone quiet. This is the deep water now." },
      { id: "conn_20", text: "The bout finds its rhythm. It is not a kind one." },
      { id: "conn_21", text: "The sand is still." },
      { id: "conn_22", text: "Wrestling. Just wrestling." },
      { id: "conn_23", text: "Two men at the limit of what they have." },
      { id: "conn_24", text: "The tawara waits." },
      { id: "conn_25", text: "One wrong move ends this. Neither man has moved wrong yet." },
      { id: "conn_26", text: "The bout is speaking its own language now. The crowd simply listens." },
      { id: "conn_27", text: "Long bouts have their own kind of beauty. The crowd is beginning to appreciate it." },
      { id: "conn_28", text: "The salt has long since settled. Everything now is earned." },
      { id: "conn_29", text: "The gyoji calls neither name. The bout is in balance." },
      { id: "conn_30", text: "Even the sand seems to wait." },
    ],
  },
};
