/**
 * Media & Scandal Engine Types
 */

import type { Id } from "./common";

/** Hidden behavioral stats for Rikishi. */
export interface RikishiBehavior {
  discipline: number; // 1-100. Low = prone to late-night drinking/fights
  mediaSavvy: number; // 1-100. High = good at hiding scandals or charming reporters
  stress: number; // Increases with losing streaks; triggers acting out
}

/** Types of media outlets in the sumo world. */
export type OutletType = 'JSA_OFFICIAL' | 'SPORTS_DAILY' | 'TABLOID';

/** A news item generated by the Media Engine. */
export interface NewsItem {
  id: string;
  date: number; // engine tick (week)
  outlet: OutletType;
  headline: string;
  bodyTokens: string; 
  targetRikishiId?: Id;
  impact: {
    moraleShift: number;
    fanPerceptionShift: number;
    fines?: number;
  };
}

/** Scandal event types for internal logic. */
export type ScandalType = 
  | 'LATE_NIGHT_BRAWL' 
  | 'SECRET_INJURY_LEAK' 
  | 'ILLEGAL_GAMBLING' 
  | 'TRAINING_ABUSE_ALLEGATION'
  | 'COACH_DISPUTE';
