/**
 * Media & Scandal Engine Types
 */

import type { Id } from "./common";

/** Hidden behavioral stats for Rikishi. */
export interface RikishiBehavior {
  discipline: number; // 1-100. Low = prone to late-night drinking/fights
  mediaSavvy: number; // 1-100. High = good at hiding scandals or charming reporters
  stress: number; // Increases with losing streaks; triggers acting out
}

/** Types of media outlets in the sumo world. */
export type OutletType = 'JSA_OFFICIAL' | 'SPORTS_DAILY' | 'TABLOID';

/** A news item generated by the Media Engine. */
export interface NewsItem {
  id: string;
  date: number; // engine tick (week)
  outlet: OutletType;
  headline: string;
  bodyTokens: string; 
  targetRikishiId?: Id;
  impact: {
    moraleShift: number;
    fanPerceptionShift: number;
    fines?: number;
  };
}

/** Scandal event types for internal logic. */
export type ScandalType = 
  | 'LATE_NIGHT_BRAWL' 
  | 'SECRET_INJURY_LEAK' 
  | 'ILLEGAL_GAMBLING' 
  | 'TRAINING_ABUSE_ALLEGATION'
  | 'COACH_DISPUTE';

/** Media tones and beats for narrative generation. */
export type MediaTone = "neutral" | "praise" | "concern" | "controversy" | "hype" | "disrespect";
export type MediaBeat = "daily_bout" | "streak" | "upset" | "title_race" | "rivalry" | "injury" | "promotion_watch" | "heya_story" | "feature" | "retirement_watch" | "discipline";
export type HeadlineTier = "local" | "national" | "main_event";

export interface MediaHeadline {
  id: string;
  week: number;
  bashoName?: string;
  tier: HeadlineTier;
  beat: MediaBeat;
  tone: MediaTone;
  rikishiIds: string[];
  heyaIds: string[];
  title: string;
  subtitle?: string;
  impact: number;
  tags: string[];
  bout?: {
    winnerId: string;
    loserId: string;
    kimarite?: string;
    upset?: boolean;
    day?: number;
    division?: string;
  };
}

export interface MediaState {
  version: string;
  headlines: MediaHeadline[];
  mediaHeat: Record<string, number>;
  heyaPressure: Record<string, number>;
  bashoStreaks: Record<string, number>;
  streakHeadlinesFired: Record<string, number[]>;
  promoWatchFired: Record<string, boolean>;
  retirementWatchFired: Record<string, boolean>;
  titleRaceDayFired: Record<number, boolean>;
  injuryWithdrawalFired: Record<string, boolean>;
}

