/**
 * OfficialsPanel — displays gyoji and shimpan pools.
 *
 * Surfaces the real gyojiPool and shimpanPool generated by WorldFactory.
 * Previously these pools existed in the world state but were never shown
 * to the player.
 */
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Gavel, Users } from "lucide-react";
import type { OfficialsProjection } from "@/presenters/officialsProjections";

export function OfficialsPanel({ projection }: { projection: OfficialsProjection }) {
  const { gyoji, shimpan, topGyoji, totalBoutsOfficiated, totalReversals } = projection;

  return (
    <div className="space-y-4" data-testid="officials-panel">
      <Card className="border-primary/20">
        <CardContent className="p-4">
          <div className="flex items-center gap-2 mb-3">
            <Gavel className="h-4 w-4 text-primary" />
            <span className="text-sm font-medium">Gyoji (Referees)</span>
            <Badge variant="outline" className="ml-auto text-xs">
              {gyoji.length} active
            </Badge>
          </div>
          {topGyoji && (
            <div className="text-xs text-muted-foreground mb-3">
              Top official: <span className="text-foreground font-medium">{topGyoji.name}</span>
              {" "}
              ({topGyoji.rankLabel}, {topGyoji.accuracy} accuracy)
            </div>
          )}
          <div className="text-xs text-muted-foreground mb-3">
            {totalBoutsOfficiated} bouts officiated · {totalReversals} calls reversed
          </div>
          <ScrollArea className="h-48">
            <div className="space-y-1">
              {gyoji.map((g) => (
                <div
                  key={g.id}
                  className="flex items-center justify-between py-1.5 px-2 rounded hover:bg-muted/30"
                  data-testid={`gyoji-row-${g.id}`}
                >
                  <div className="flex items-center gap-2">
                    <span className="text-sm font-medium">{g.name}</span>
                    <Badge variant="outline" className="text-[9px] uppercase tracking-widest">
                      {g.rankLabel}
                    </Badge>
                  </div>
                  <div className="flex items-center gap-3 text-xs tabular-nums">
                    <span className="text-muted-foreground">{g.boutsOfficiated} bouts</span>
                    <span className="text-muted-foreground">{g.callsReversed} reversed</span>
                    <span
                      className={
                        g.accuracy >= 75
                          ? "text-primary font-medium"
                          : g.accuracy >= 60
                            ? "text-gold"
                            : "text-destructive"
                      }
                    >
                      {g.accuracy}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </ScrollArea>
        </CardContent>
      </Card>

      <Card className="border-primary/20">
        <CardContent className="p-4">
          <div className="flex items-center gap-2 mb-3">
            <Users className="h-4 w-4 text-primary" />
            <span className="text-sm font-medium">Shimpan (Judges)</span>
            <Badge variant="outline" className="ml-auto text-xs">
              {shimpan.length} active
            </Badge>
          </div>
          <ScrollArea className="h-32">
            <div className="space-y-1">
              {shimpan.map((s) => (
                <div
                  key={s.id}
                  className="flex items-center justify-between py-1.5 px-2 rounded hover:bg-muted/30"
                  data-testid={`shimpan-row-${s.id}`}
                >
                  <span className="text-sm font-medium">{s.name}</span>
                  <div className="flex items-center gap-3 text-xs tabular-nums">
                    <span className="text-muted-foreground">{s.consultations} consultations</span>
                    <span
                      className={
                        s.accuracy >= 75
                          ? "text-primary font-medium"
                          : s.accuracy >= 60
                            ? "text-gold"
                            : "text-destructive"
                      }
                    >
                      {s.accuracy}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </ScrollArea>
        </CardContent>
      </Card>
    </div>
  );
}
